import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { apiFetch } from '../api/client'

export interface BackupStatus {
  last_backup_at: string | null
  stale: boolean
}

export function useBackupStatus() {
  return useQuery<BackupStatus>({
    queryKey: ['dashboard', 'backup-status'],
    queryFn: () => apiFetch<BackupStatus>('/dashboard/backup-status'),
    staleTime: 5 * 60_000,
  })
}

export interface ScoreConfig {
  base_score: number
  crit_penalty: number
  crit_penalty_cap: number
  high_penalty: number
  high_penalty_cap: number
  breach_penalty: number
  breach_penalty_cap: number
  fw_bonus: number
  fw_bonus_cap: number
}

export function useScoreConfig() {
  return useQuery<ScoreConfig>({
    queryKey: ['dashboard', 'score-config'],
    queryFn: () => apiFetch<ScoreConfig>('/dashboard/score/config'),
  })
}

export function useUpdateScoreConfig() {
  const qc = useQueryClient()
  return useMutation<ScoreConfig, Error, ScoreConfig>({
    mutationFn: (data) => apiFetch<ScoreConfig>('/dashboard/score/config', { method: 'PUT', body: JSON.stringify(data) }),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ['dashboard', 'score-config'] })
      void qc.invalidateQueries({ queryKey: ['dashboard', 'score'] })
    },
  })
}

/**
 * Composite security health score returned by the cross-module dashboard endpoint.
 * The `score` is a 0–100 integer derived from the weighted component counts below.
 */
export interface DashboardScore {
  /** Aggregated security health score (0 = critical risk, 100 = fully compliant). */
  score: number
  components: {
    /** Number of open findings at critical severity across all SecPulse scans. */
    critical_findings: number
    /** Number of open findings at high severity across all SecPulse scans. */
    high_findings: number
    /** Unresolved data-breach events in the SecVitals incident register. */
    open_breaches: number
    /** Compliance frameworks currently tracked in SecVitals. */
    active_frameworks: number
  }
}

/**
 * Fetches the current cross-module security health score.
 * Data is considered fresh for 60 seconds; background refetches keep the header
 * score indicator up-to-date without hammering the API on every render.
 */
export function useDashboardScore() {
  return useQuery<DashboardScore>({
    queryKey: ['dashboard', 'score'],
    queryFn: () => apiFetch<DashboardScore>('/dashboard/score'),
    staleTime: 10_000,
  })
}

/**
 * A single in-app notification generated by any Vakt module.
 */
export interface UserNotification {
  id: string
  title: string
  /** Full notification body — may contain markdown. */
  body: string
  /** Severity level; drives the icon and colour shown in the notification list. */
  type: 'info' | 'warning' | 'error'
  /** Source module identifier (e.g. `"secpulse"`, `"secvitals"`). */
  module: string
  /** Whether the current user has already seen the notification. */
  read: boolean
  /** RFC 3339 UTC timestamp of when the notification was created. */
  created_at: string
}

/**
 * Fetches the current user's notification list.
 *
 * Sprint 17 S17-4: Polling-Interval entfernt — der NotificationBell verbindet
 * sich jetzt zusätzlich mit useNotificationStream und ruft bei jeder neuen
 * Notification queryClient.invalidateQueries(['dashboard', 'notifications'])
 * auf. staleTime bleibt 30 s als Cache-Hint für TabSwitch-Refetches.
 */
export function useNotifications() {
  return useQuery<UserNotification[]>({
    queryKey: ['dashboard', 'notifications'],
    queryFn: () => apiFetch<UserNotification[]>('/dashboard/notifications'),
    staleTime: 30_000,
  })
}

/**
 * Marks a single notification as read by its ID and invalidates the list cache.
 * The mutation variable is the notification `id` string.
 */
export function useMarkNotificationRead() {
  const queryClient = useQueryClient()
  return useMutation<undefined, Error, string>({
    mutationFn: (id) => apiFetch<undefined>(`/dashboard/notifications/${id}/read`, { method: 'POST' }),
    onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['dashboard', 'notifications'] }) },
  })
}

/**
 * Marks every unread notification as read in a single API call,
 * then invalidates the notification list so the bell badge clears immediately.
 */
export function useMarkAllRead() {
  const queryClient = useQueryClient()
  return useMutation<undefined>({
    mutationFn: () => apiFetch<undefined>('/dashboard/notifications/read-all', { method: 'POST' }),
    onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['dashboard', 'notifications'] }) },
  })
}

// ---------------------------------------------------------------------------
// Aggregate dashboard — executive compliance summary
// ---------------------------------------------------------------------------

export interface FrameworkScore {
  framework_id: string
  framework_name: string
  total_controls: number
  implemented_controls: number
  score_pct: number
}

export interface RiskSummary {
  id: string
  title: string
  likelihood: number
  impact: number
  score: number
  status: string
}

export interface ActivityEntry {
  id: string
  action: string
  entity_type: string
  user_email: string
  created_at: string
}

export interface DashboardAggregate {
  framework_scores: FrameworkScore[]
  open_capas: number
  overdue_controls: number
  overdue_tasks: number
  critical_risks: number
  top_risks: RiskSummary[]
  recent_activity: ActivityEntry[]
  policies_total: number
  policies_approved: number
}

/**
 * Fetches the aggregated executive compliance summary.
 * Refreshes every 60 seconds and on window focus.
 */
export function useDashboardAggregate() {
  return useQuery<DashboardAggregate>({
    queryKey: ['dashboard', 'aggregate'],
    queryFn: () => apiFetch<DashboardAggregate>('/dashboard/aggregate'),
    staleTime: 30_000,
    refetchInterval: 60_000,
  })
}
