// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCKCollectorEvidence(ctx context.Context, arg AddCKCollectorEvidenceParams) (AddCKCollectorEvidenceRow, error)
	// ── Evidence ────────────────────────────────────────────────────────────────
	AddCKEvidence(ctx context.Context, arg AddCKEvidenceParams) (AddCKEvidenceRow, error)
	// ── Control Changelog ───────────────────────────────────────────────────────
	AppendCKControlChange(ctx context.Context, arg AppendCKControlChangeParams) error
	ApplyCKApprovedControlStatus(ctx context.Context, arg ApplyCKApprovedControlStatusParams) error
	ApprovePPDPIA(ctx context.Context, arg ApprovePPDPIAParams) (PoDpias, error)
	// ── Controls ────────────────────────────────────────────────────────────────
	// Caller iterates per Control inside a tx (r.q.WithTx(tx)). Title/description
	// werden bei (framework_id, control_id)-Duplikat aktualisiert — andere Felder
	// bleiben intakt (z.B. manuell gesetztes manual_status).
	BulkInsertCKControl(ctx context.Context, arg BulkInsertCKControlParams) error
	BulkUpdateCKCAPAStatus(ctx context.Context, arg BulkUpdateCKCAPAStatusParams) (int64, error)
	// ── Bulk-Control-Status ─────────────────────────────────────────────────────
	BulkUpdateCKControlStatus(ctx context.Context, arg BulkUpdateCKControlStatusParams) error
	// Bulk-Update über IN-Liste via UUID-Array.
	BulkUpdateSPFindings(ctx context.Context, arg BulkUpdateSPFindingsParams) (int64, error)
	CKFrameworkExists(ctx context.Context, arg CKFrameworkExistsParams) (bool, error)
	CKSupplierExists(ctx context.Context, arg CKSupplierExistsParams) (bool, error)
	CountCKAISystemsWithoutDocs(ctx context.Context, orgID string) (int64, error)
	CountCKCAPAs(ctx context.Context, arg CountCKCAPAsParams) (int64, error)
	CountCKControls(ctx context.Context, arg CountCKControlsParams) (int64, error)
	// Returns one row per control_id with the count of approved+pending evidence.
	CountCKEvidenceByControl(ctx context.Context, arg CountCKEvidenceByControlParams) ([]CountCKEvidenceByControlRow, error)
	// Anzahl auf 'implemented' gesetzter Controls seit einem Zeitpunkt (Executive Summary / Board Report).
	CountCKClosedControlsSince(ctx context.Context, arg CountCKClosedControlsSinceParams) (int32, error)
	// Checks whether a milestone notification has already been sent (dedupe key = "<frameworkID>:<threshold>").
	CountCKFrameworkMilestoneNotifs(ctx context.Context, arg CountCKFrameworkMilestoneNotifsParams) (int64, error)
	CountCKIncidents(ctx context.Context, orgID string) (int64, error)
	// Anzahl neu eröffneter Incidents seit einem Zeitpunkt (Executive Summary).
	CountCKIncidentsSince(ctx context.Context, arg CountCKIncidentsSinceParams) (int32, error)
	// Anzahl Incidents der letzten 30 Tage für den Board-Report.
	CountCKRecentIncidents(ctx context.Context, arg CountCKRecentIncidentsParams) (int32, error)
	CountCKPendingApprovals(ctx context.Context, orgID string) (int64, error)
	CountCKPolicies(ctx context.Context, orgID string) (int64, error)
	CountCKRisks(ctx context.Context, orgID string) (int64, error)
	CountHREmployees(ctx context.Context, orgID string) (int64, error)
	CountPPBreaches(ctx context.Context, orgID string) (int64, error)
	CountPPVVT(ctx context.Context, orgID string) (int64, error)
	CountSPAssets(ctx context.Context, arg CountSPAssetsParams) (int64, error)
	CountSVDismissals(ctx context.Context, arg CountSVDismissalsParams) (int32, error)
	CountSVProjectAccessLog(ctx context.Context, arg CountSVProjectAccessLogParams) (int32, error)
	CountSPFindings(ctx context.Context, arg CountSPFindingsParams) (int64, error)
	// Anzahl auf 'resolved' gesetzter Findings seit einem Zeitpunkt (Executive Summary).
	CountSPResolvedFindingsSince(ctx context.Context, arg CountSPResolvedFindingsSinceParams) (int32, error)
	// ── Tracking events ───────────────────────────────────────────────────────
	CountSREventsByType(ctx context.Context, arg CountSREventsByTypeParams) (int64, error)
	CountSRTargetsInGroup(ctx context.Context, groupID string) (int64, error)
	// ── AI Systems (EU AI Act) ──────────────────────────────────────────────────
	CreateCKAISystem(ctx context.Context, arg CreateCKAISystemParams) (CkAiSystems, error)
	// ── Access Review Campaigns ────────────────────────────────────────────────
	CreateCKAccessReviewCampaign(ctx context.Context, arg CreateCKAccessReviewCampaignParams) (CkAccessReviewCampaigns, error)
	// ── Access Review Items ────────────────────────────────────────────────────
	CreateCKAccessReviewItem(ctx context.Context, arg CreateCKAccessReviewItemParams) (CkAccessReviewItems, error)
	// ── Control Approvals ──────────────────────────────────────────────────────
	CreateCKApprovalRequest(ctx context.Context, arg CreateCKApprovalRequestParams) (CkControlApprovals, error)
	// ── Assessments (Supplier-Portal) ───────────────────────────────────────────
	CreateCKAssessment(ctx context.Context, arg CreateCKAssessmentParams) error
	// ── Audit Records ───────────────────────────────────────────────────────────
	CreateCKAuditRecord(ctx context.Context, arg CreateCKAuditRecordParams) (CreateCKAuditRecordRow, error)
	// ── Auditor Links ───────────────────────────────────────────────────────────
	CreateCKAuditorLink(ctx context.Context, arg CreateCKAuditorLinkParams) (CreateCKAuditorLinkRow, error)
	// ── CAPAs (Corrective and Preventive Actions) ───────────────────────────────
	CreateCKCAPA(ctx context.Context, arg CreateCKCAPAParams) (CkCapas, error)
	// ── CCM (Continuous Control Monitoring) ────────────────────────────────────
	CreateCKCCMCheck(ctx context.Context, arg CreateCKCCMCheckParams) (CreateCKCCMCheckRow, error)
	CreateCKComment(ctx context.Context, arg CreateCKCommentParams) (CkComments, error)
	CreateCKControlException(ctx context.Context, arg CreateCKControlExceptionParams) (CkControlExceptions, error)
	CreateCKControlTask(ctx context.Context, arg CreateCKControlTaskParams) (CkControlTasks, error)
	// ── Evidence Files ─────────────────────────────────────────────────────────
	CreateCKEvidenceFile(ctx context.Context, arg CreateCKEvidenceFileParams) (CkEvidenceFiles, error)
	// Vakt Comply queries — sqlc migration in v0.6.x (ADR-0005).
	//
	// Migrationsstand:
	//   ✅ ck_frameworks — sqlc (this file)
	//   ⏳ ck_controls / ck_evidence / ck_risks / ck_incidents / ck_policies /
	//      ck_audits / ... — embedded SQL (Sitzungen E/F)
	// ── Frameworks ──────────────────────────────────────────────────────────────
	CreateCKFramework(ctx context.Context, arg CreateCKFrameworkParams) (CkFrameworks, error)
	// ── Incidents ───────────────────────────────────────────────────────────────
	CreateCKIncident(ctx context.Context, arg CreateCKIncidentParams) (CreateCKIncidentRow, error)
	// ── Framework Mappings (Story 28.2) ─────────────────────────────────────────
	CreateCKMapping(ctx context.Context, arg CreateCKMappingParams) (CkFrameworkMappings, error)
	CreateCKMeasure(ctx context.Context, arg CreateCKMeasureParams) (CkControlMeasures, error)
	// ── Audit Milestones ───────────────────────────────────────────────────────
	CreateCKMilestone(ctx context.Context, arg CreateCKMilestoneParams) (CreateCKMilestoneRow, error)
	// ── Policies ────────────────────────────────────────────────────────────────
	CreateCKPolicy(ctx context.Context, arg CreateCKPolicyParams) (CreateCKPolicyRow, error)
	// ── Policy Acceptance (s26-sqlc-vitals-5 — DSGVO-sensitiv) ─────────────────
	CreateCKPolicyAcceptanceCampaign(ctx context.Context, arg CreateCKPolicyAcceptanceCampaignParams) (CreateCKPolicyAcceptanceCampaignRow, error)
	CreateCKPolicyAcceptanceRequest(ctx context.Context, arg CreateCKPolicyAcceptanceRequestParams) (string, error)
	CreateCKQuestion(ctx context.Context, arg CreateCKQuestionParams) (CkQuestionnaireQuestions, error)
	// ── Questionnaires ──────────────────────────────────────────────────────────
	CreateCKQuestionnaire(ctx context.Context, arg CreateCKQuestionnaireParams) (CkQuestionnaires, error)
	// ── Resilience Tests (DORA Art. 24-27) ─────────────────────────────────────
	CreateCKResilienceTest(ctx context.Context, arg CreateCKResilienceTestParams) (CkResilienceTests, error)
	// ── Risks ───────────────────────────────────────────────────────────────────
	// risk_score ist GENERATED ALWAYS (likelihood * impact) — wird nicht direkt
	// gesetzt. CreateRisk/UpdateRisk lassen die Spalte aus dem INSERT/SET, sie
	// erscheint nur im RETURNING.
	CreateCKRisk(ctx context.Context, arg CreateCKRiskParams) (CreateCKRiskRow, error)
	// ── Suppliers (NIS2 Art. 21 / DORA Art. 28) ─────────────────────────────────
	CreateCKSupplier(ctx context.Context, arg CreateCKSupplierParams) (CreateCKSupplierRow, error)
	// ── Collaborative Tasks ─────────────────────────────────────────────────────
	CreateCKTask(ctx context.Context, arg CreateCKTaskParams) (CkTasks, error)
	CreateHRChecklist(ctx context.Context, arg CreateHRChecklistParams) (HrChecklists, error)
	CreateHREmployee(ctx context.Context, arg CreateHREmployeeParams) (HrEmployees, error)
	CreatePPAVV(ctx context.Context, arg CreatePPAVVParams) (CreatePPAVVRow, error)
	CreatePPAVVWithBody(ctx context.Context, arg CreatePPAVVWithBodyParams) (CreatePPAVVWithBodyRow, error)
	CreatePPBreach(ctx context.Context, arg CreatePPBreachParams) (PoBreaches, error)
	CreatePPDPIA(ctx context.Context, arg CreatePPDPIAParams) (PoDpias, error)
	CreatePPDSR(ctx context.Context, arg CreatePPDSRParams) (CreatePPDSRRow, error)
	CreatePPVVT(ctx context.Context, arg CreatePPVVTParams) (PoVvtEntries, error)
	CreatePortalPPDSR(ctx context.Context, arg CreatePortalPPDSRParams) (string, error)
	// Vakt Scan queries — sqlc migration in v0.6.x (ADR-0005).
	//
	// Migrationsstand:
	//   ✅ vb_assets     — sqlc (this file)
	//   ✅ vb_sla_config — sqlc
	//   ✅ vb_scans      — sqlc
	//   ⏳ vb_findings   — embedded SQL (Sitzung C2 — Dedup-Logik)
	//   ⏳ vb_components / vb_sboms / vb_reports / vb_finding_suppressions /
	//      vb_scan_schedules / vb_eol_cache — embedded SQL (Sitzung C3)
	// ── Assets ──────────────────────────────────────────────────────────────────
	CreateSPAsset(ctx context.Context, arg CreateSPAssetParams) (CreateSPAssetRow, error)
	// ── Reports ─────────────────────────────────────────────────────────────────
	CreateSPReport(ctx context.Context, arg CreateSPReportParams) (CreateSPReportRow, error)
	// ── SBOM ────────────────────────────────────────────────────────────────────
	CreateSPSBOM(ctx context.Context, arg CreateSPSBOMParams) (string, error)
	// ── Scans ───────────────────────────────────────────────────────────────────
	CreateSPScan(ctx context.Context, arg CreateSPScanParams) (VbScans, error)
	// ── Scan Schedules ──────────────────────────────────────────────────────────
	CreateSPScanSchedule(ctx context.Context, arg CreateSPScanScheduleParams) (VbScanSchedules, error)
	// ── Suppression Rules ───────────────────────────────────────────────────────
	CreateSPSuppression(ctx context.Context, arg CreateSPSuppressionParams) (VbFindingSuppressions, error)
	// ── Campaigns ─────────────────────────────────────────────────────────────
	CreateSRCampaign(ctx context.Context, arg CreateSRCampaignParams) (CreateSRCampaignRow, error)
	// ── Landing pages ─────────────────────────────────────────────────────────
	CreateSRLandingPage(ctx context.Context, arg CreateSRLandingPageParams) (SrLandingPages, error)
	CreateSRPhishReport(ctx context.Context, arg CreateSRPhishReportParams) (SrPhishReports, error)
	// ── Target groups ─────────────────────────────────────────────────────────
	CreateSRTargetGroup(ctx context.Context, arg CreateSRTargetGroupParams) (SrTargetGroups, error)
	// Vakt Aware (Phishing-Simulation & Awareness-Training)
	//
	// Tabellen-Präfix `sr_*` seit Migration 122 (vorher `pg_*` — kollidierte
	// mit dem PostgreSQL-System-Katalog-Namespace und blockierte den
	// sqlc-Parser, siehe ADR-0005).
	// ── Templates ─────────────────────────────────────────────────────────────
	CreateSRTemplate(ctx context.Context, arg CreateSRTemplateParams) (SrTemplates, error)
	CreateSRTrackingEvent(ctx context.Context, arg CreateSRTrackingEventParams) error
	// ── Training modules ──────────────────────────────────────────────────────
	CreateSRTrainingModule(ctx context.Context, arg CreateSRTrainingModuleParams) (SrTrainingModules, error)
	CreateSVAPIToken(ctx context.Context, arg CreateSVAPITokenParams) (CreateSVAPITokenRow, error)
	// ── Environments ────────────────────────────────────────────────────────────
	CreateSVEnvironment(ctx context.Context, arg CreateSVEnvironmentParams) (SoEnvironments, error)
	CreateSVGitScan(ctx context.Context, arg CreateSVGitScanParams) (SVGitScanRow, error)
	CreateSVShareLink(ctx context.Context, arg CreateSVShareLinkParams) (CreateSVShareLinkRow, error)
	// SecVault queries — migrated to sqlc in Sprint 11+ (ADR-0005, inkrementell).
	//
	// Migrationspfad:
	//   ✅ Projects, Environments, AccessLog, RotationPolicies — sqlc (this file)
	//   ⏳ Secrets — bleibt embedded SQL in repository.go (Crypto-Felder + dynamische
	//      Spalten-Auswahl je nach decrypt-Strategie machen sqlc-Generierung holprig).
	//      Migration on-demand bei nächstem Secrets-Refactor.
	// ── Projects ────────────────────────────────────────────────────────────────
	CreateSVProject(ctx context.Context, arg CreateSVProjectParams) (CreateSVProjectRow, error)
	DeleteCKAISystem(ctx context.Context, arg DeleteCKAISystemParams) (int64, error)
	DeleteCKAccessReviewCampaign(ctx context.Context, arg DeleteCKAccessReviewCampaignParams) (int64, error)
	DeleteCKCAPA(ctx context.Context, arg DeleteCKCAPAParams) (int64, error)
	DeleteCKCCMCheck(ctx context.Context, arg DeleteCKCCMCheckParams) (int64, error)
	DeleteCKComment(ctx context.Context, arg DeleteCKCommentParams) (int64, error)
	DeleteCKControlException(ctx context.Context, arg DeleteCKControlExceptionParams) (int64, error)
	DeleteCKControlTask(ctx context.Context, arg DeleteCKControlTaskParams) (int64, error)
	DeleteCKEvidenceFile(ctx context.Context, arg DeleteCKEvidenceFileParams) (CkEvidenceFiles, error)
	DeleteCKFramework(ctx context.Context, arg DeleteCKFrameworkParams) (int64, error)
	DeleteCKMapping(ctx context.Context, arg DeleteCKMappingParams) (int64, error)
	DeleteCKMeasure(ctx context.Context, arg DeleteCKMeasureParams) (int64, error)
	DeleteCKMilestone(ctx context.Context, arg DeleteCKMilestoneParams) (int64, error)
	DeleteCKQuestion(ctx context.Context, arg DeleteCKQuestionParams) (int64, error)
	DeleteCKQuestionnaire(ctx context.Context, arg DeleteCKQuestionnaireParams) (int64, error)
	DeleteCKResilienceTest(ctx context.Context, arg DeleteCKResilienceTestParams) (int64, error)
	DeleteCKSupplier(ctx context.Context, arg DeleteCKSupplierParams) (int64, error)
	DeleteCKTask(ctx context.Context, arg DeleteCKTaskParams) (int64, error)
	DeleteHRChecklist(ctx context.Context, arg DeleteHRChecklistParams) error
	DeleteHREmployee(ctx context.Context, arg DeleteHREmployeeParams) error
	DeletePPAVV(ctx context.Context, arg DeletePPAVVParams) error
	DeletePPBreach(ctx context.Context, arg DeletePPBreachParams) error
	DeletePPDPIA(ctx context.Context, arg DeletePPDPIAParams) error
	DeletePPDSR(ctx context.Context, arg DeletePPDSRParams) error
	DeletePPVVT(ctx context.Context, arg DeletePPVVTParams) error
	DeleteSPScanSchedule(ctx context.Context, arg DeleteSPScanScheduleParams) (int64, error)
	DeleteSPSuppression(ctx context.Context, arg DeleteSPSuppressionParams) (int64, error)
	DeleteSVEnvironment(ctx context.Context, arg DeleteSVEnvironmentParams) (int64, error)
	DeleteSVProject(ctx context.Context, arg DeleteSVProjectParams) (int64, error)
	DeleteSVSecret(ctx context.Context, arg DeleteSVSecretParams) (int64, error)
	DismissSVScanResult(ctx context.Context, arg DismissSVScanResultParams) (int64, error)
	DeleteUserModulePermissions(ctx context.Context, arg DeleteUserModulePermissionsParams) error
	ExecutePPDSRErasure(ctx context.Context, arg ExecutePPDSRErasureParams) (ExecutePPDSRErasureRow, error)
	FindActiveSRCampaignForReporter(ctx context.Context, arg FindActiveSRCampaignForReporterParams) (string, error)
	FindCKControlByCode(ctx context.Context, arg FindCKControlByCodeParams) (string, error)
	// Erwartet bereits %-umschlossene Keywords (z.B. "%firewall%").
	FindCKControlsByKeywords(ctx context.Context, arg FindCKControlsByKeywordsParams) ([]FindCKControlsByKeywordsRow, error)
	// Sicherheitshinweis: sa.org_id war früher Bestandteil dieser Query, existiert
	// aber auf ck_supplier_answers nicht. Die Org-Eingrenzung läuft über den JOIN
	// auf ck_supplier_assessments.org_id.
	FindCKExpiringCerts(ctx context.Context, arg FindCKExpiringCertsParams) ([]FindCKExpiringCertsRow, error)
	FindCKFrameworkByName(ctx context.Context, arg FindCKFrameworkByNameParams) (CkFrameworks, error)
	// ── Control Discovery (used by SecPulse auto-evidence + AI classifier) ────
	FindCKPatchControls(ctx context.Context, orgID string) ([]FindCKPatchControlsRow, error)
	FirstHRChecklistByType(ctx context.Context, arg FirstHRChecklistByTypeParams) (HrChecklists, error)
	// Liefert pro Framework: Gesamtanzahl Controls + Anzahl implemented (Board Report Score).
	GetBoardReportComplianceScoreRows(ctx context.Context, orgID string) ([]GetBoardReportComplianceScoreRowsRow, error)
	GetCKAISystem(ctx context.Context, arg GetCKAISystemParams) (CkAiSystems, error)
	GetCKAccessReviewCampaign(ctx context.Context, arg GetCKAccessReviewCampaignParams) (CkAccessReviewCampaigns, error)
	GetCKAnswerWithQuestion(ctx context.Context, arg GetCKAnswerWithQuestionParams) (GetCKAnswerWithQuestionRow, error)
	GetCKAnswersForAssessment(ctx context.Context, arg GetCKAnswersForAssessmentParams) ([]GetCKAnswersForAssessmentRow, error)
	GetCKApproval(ctx context.Context, arg GetCKApprovalParams) (CkControlApprovals, error)
	// Used by GetAssessmentWithQuestionnaire (Composer-Pattern).
	GetCKAssessmentBase(ctx context.Context, id string) (CkSupplierAssessments, error)
	GetCKAssessmentByTokenHash(ctx context.Context, tokenHash string) (CkSupplierAssessments, error)
	GetCKAuditRecord(ctx context.Context, arg GetCKAuditRecordParams) (GetCKAuditRecordRow, error)
	GetCKAuditorLinkByHash(ctx context.Context, tokenHash string) (GetCKAuditorLinkByHashRow, error)
	GetCKAuditorLinkByID(ctx context.Context, arg GetCKAuditorLinkByIDParams) (GetCKAuditorLinkByIDRow, error)
	GetCKCAPA(ctx context.Context, arg GetCKCAPAParams) (CkCapas, error)
	GetCKCCMCheck(ctx context.Context, arg GetCKCCMCheckParams) (GetCKCCMCheckRow, error)
	GetCKControl(ctx context.Context, arg GetCKControlParams) (GetCKControlRow, error)
	GetCKEvidence(ctx context.Context, arg GetCKEvidenceParams) (GetCKEvidenceRow, error)
	GetCKEvidenceFile(ctx context.Context, arg GetCKEvidenceFileParams) (CkEvidenceFiles, error)
	// Within a single framework; only approved evidence.
	GetCKExpiringEvidence(ctx context.Context, arg GetCKExpiringEvidenceParams) ([]GetCKExpiringEvidenceRow, error)
	GetCKExpiringEvidenceAllFrameworks(ctx context.Context, arg GetCKExpiringEvidenceAllFrameworksParams) ([]GetCKExpiringEvidenceAllFrameworksRow, error)
	// Pro Framework: Name, Gesamtanzahl Controls, Anzahl implemented (Executive Summary PDF Section 2).
	GetExecutiveFrameworkScores(ctx context.Context, orgID string) ([]GetExecutiveFrameworkScoresRow, error)
	// Top-5 offene Risiken nach Score für Executive Summary PDF Section 3.
	GetExecutiveTopRisks(ctx context.Context, orgID string) ([]GetExecutiveTopRisksRow, error)
	GetCKFramework(ctx context.Context, arg GetCKFrameworkParams) (CkFrameworks, error)
	GetCKIncident(ctx context.Context, arg GetCKIncidentParams) (GetCKIncidentRow, error)
	GetCKIncidentReportPDF(ctx context.Context, arg GetCKIncidentReportPDFParams) ([]byte, error)
	GetCKMappingsBySourceControlIDs(ctx context.Context, arg GetCKMappingsBySourceControlIDsParams) ([]CkFrameworkMappings, error)
	GetCKMilestone(ctx context.Context, arg GetCKMilestoneParams) (GetCKMilestoneRow, error)
	GetCKOrgAdminEmails(ctx context.Context, orgID string) ([]string, error)
	GetCKOrgMemberRole(ctx context.Context, arg GetCKOrgMemberRoleParams) (string, error)
	GetCKOrgApprovalRequired(ctx context.Context, id string) (bool, error)
	// Liest den Org-Namen für Akzeptanz-Kampagnen-Emails (s26-sqlc-vitals-5).
	GetCKOrgName(ctx context.Context, id string) (string, error)
	GetCKOrgSector(ctx context.Context, id string) (GetCKOrgSectorRow, error)
	GetCKPolicy(ctx context.Context, arg GetCKPolicyParams) (GetCKPolicyRow, error)
	// Aggregiert Total/Accepted/Pending für eine Akzeptanz-Kampagne.
	GetCKPolicyAcceptanceCampaignStats(ctx context.Context, campaignID string) (GetCKPolicyAcceptanceCampaignStatsRow, error)
	// Öffentliche Info für das Accept-Portal (Token-basiert, kein Auth).
	GetCKPolicyAcceptancePublicInfo(ctx context.Context, tokenHash string) (GetCKPolicyAcceptancePublicInfoRow, error)
	// Liest Request + Policy-Titel + Org-ID für den Token-basierten Accept-Flow.
	GetCKPolicyAcceptanceRequestByToken(ctx context.Context, tokenHash string) (GetCKPolicyAcceptanceRequestByTokenRow, error)
	// Returns a single DB-backed compliance template by UUID.
	GetCKPolicyTemplateByID(ctx context.Context, id string) (GetCKPolicyTemplateByIDRow, error)
	// Letzter Score-Snapshot vor heute (Board-Report Delta).
	GetCKPreviousScore(ctx context.Context, orgID string) (float64, error)
	GetCKPolicyVersion(ctx context.Context, arg GetCKPolicyVersionParams) (CkPolicyVersions, error)
	GetCKQuestion(ctx context.Context, arg GetCKQuestionParams) (CkQuestionnaireQuestions, error)
	GetCKQuestionnaireBase(ctx context.Context, arg GetCKQuestionnaireBaseParams) (CkQuestionnaires, error)
	GetCKResilienceTest(ctx context.Context, arg GetCKResilienceTestParams) (CkResilienceTests, error)
	GetCKRisk(ctx context.Context, arg GetCKRiskParams) (GetCKRiskRow, error)
	// Aggregiert pro Tag (TO_CHAR auf UTC); MAX statt LAST/FIRST_VALUE weil
	// mehrere Snapshots am gleichen Tag normaler Fall sind. Score wird in
	// float8 gecastet damit sqlc keinen interface{}-Typ generiert.
	GetCKScoreHistory(ctx context.Context, arg GetCKScoreHistoryParams) ([]GetCKScoreHistoryRow, error)
	GetCKSupplier(ctx context.Context, arg GetCKSupplierParams) (GetCKSupplierRow, error)
	// Minimal projection für den Expiry-Notifier-Worker; nur Evidence die
	// noch nicht benachrichtigt wurde (expiry_notified_at IS NULL).
	GetCKUnnotifiedExpiringEvidence(ctx context.Context, arg GetCKUnnotifiedExpiringEvidenceParams) ([]GetCKUnnotifiedExpiringEvidenceRow, error)
	GetDSRPortalSettings(ctx context.Context, id string) (GetDSRPortalSettingsRow, error)
	GetHRChecklist(ctx context.Context, arg GetHRChecklistParams) (HrChecklists, error)
	GetHRChecklistRun(ctx context.Context, arg GetHRChecklistRunParams) (HrChecklistRuns, error)
	GetHREmployee(ctx context.Context, arg GetHREmployeeParams) (HrEmployees, error)
	GetHREmployeeByEmail(ctx context.Context, arg GetHREmployeeByEmailParams) (HrEmployees, error)
	// ── HR user-revocation helpers (sessions/users/api_keys — cross-module) ─
	HRDisableUser(ctx context.Context, arg HRDisableUserParams) error
	HRRevokeUserAPIKeys(ctx context.Context, arg HRRevokeUserAPIKeysParams) error
	HRRevokeUserSessions(ctx context.Context, arg HRRevokeUserSessionsParams) error
	GetLatestCKAIDocumentation(ctx context.Context, arg GetLatestCKAIDocumentationParams) (CkAiDocumentation, error)
	GetLatestSPSBOM(ctx context.Context, arg GetLatestSPSBOMParams) (GetLatestSPSBOMRow, error)
	// ── DSR Portal Settings (on organizations table) ────────────────────────────
	GetOrgByDSRSlug(ctx context.Context, dsrPortalSlug pgtype.Text) (GetOrgByDSRSlugRow, error)
	// ── Phish-Button (Feature 5) ──────────────────────────────────────────────
	GetOrgByPhishReportToken(ctx context.Context, phishReportToken pgtype.Text) (string, error)
	GetPPAVV(ctx context.Context, arg GetPPAVVParams) (GetPPAVVRow, error)
	GetPPBreach(ctx context.Context, arg GetPPBreachParams) (PoBreaches, error)
	GetPPDPIA(ctx context.Context, arg GetPPDPIAParams) (PoDpias, error)
	GetPPDSR(ctx context.Context, arg GetPPDSRParams) (GetPPDSRRow, error)
	GetPPDSRByTokenHash(ctx context.Context, tokenHash pgtype.Text) (GetPPDSRByTokenHashRow, error)
	GetPPVVT(ctx context.Context, arg GetPPVVTParams) (PoVvtEntries, error)
	GetSPAsset(ctx context.Context, arg GetSPAssetParams) (GetSPAssetRow, error)
	GetSPAssetByName(ctx context.Context, arg GetSPAssetByNameParams) (GetSPAssetByNameRow, error)
	// ── EOL Cache ───────────────────────────────────────────────────────────────
	GetSPEOLCache(ctx context.Context, arg GetSPEOLCacheParams) (GetSPEOLCacheRow, error)
	// ── Findings (Read + Update) ────────────────────────────────────────────────
	// Upsert/Dedup queries (UpsertFinding, BatchUpsertFindings) remain embedded for
	// now — their business logic (cve_id vs template_id dedup, reopen_count rules,
	// source-set merge) is hard to express as a single sqlc query and currently
	// sits in the repository (Sitzung C2b).
	GetSPFinding(ctx context.Context, arg GetSPFindingParams) (VbFindings, error)
	GetSPReport(ctx context.Context, arg GetSPReportParams) (GetSPReportRow, error)
	GetSPReportContent(ctx context.Context, arg GetSPReportContentParams) (GetSPReportContentRow, error)
	// ── Risk Trend ──────────────────────────────────────────────────────────────
	// Aggregates open findings per day for the last :days days.
	GetSPRiskTrend(ctx context.Context, arg GetSPRiskTrendParams) ([]GetSPRiskTrendRow, error)
	// ── SLA-Config ──────────────────────────────────────────────────────────────
	GetSPSLAConfig(ctx context.Context, orgID string) (GetSPSLAConfigRow, error)
	GetSPSLADashboard(ctx context.Context, orgID string) ([]GetSPSLADashboardRow, error)
	GetSPScan(ctx context.Context, arg GetSPScanParams) (VbScans, error)
	GetSRAssignment(ctx context.Context, arg GetSRAssignmentParams) (SrAssignments, error)
	GetSRCampaign(ctx context.Context, arg GetSRCampaignParams) (GetSRCampaignRow, error)
	GetSRCampaignByTrackingToken(ctx context.Context, trackingToken string) (GetSRCampaignByTrackingTokenRow, error)
	GetSRCampaignGroupID(ctx context.Context, id string) (pgtype.UUID, error)
	GetSRCompletionByAssignment(ctx context.Context, arg GetSRCompletionByAssignmentParams) (SrCompletions, error)
	GetSRLandingPageForCampaign(ctx context.Context, id string) (SrLandingPages, error)
	// ── SecReflex cross-table lookups ─────────────────────────────────────────
	GetSROrganizationName(ctx context.Context, id string) (string, error)
	GetSRPhishReportStats(ctx context.Context, orgID string) (GetSRPhishReportStatsRow, error)
	GetSRTargetEmail(ctx context.Context, id string) (string, error)
	GetSRTemplate(ctx context.Context, arg GetSRTemplateParams) (SrTemplates, error)
	GetSRTrainingModuleByAttackType(ctx context.Context, arg GetSRTrainingModuleByAttackTypeParams) (SrTrainingModules, error)
	GetSRTrainingModuleByID(ctx context.Context, arg GetSRTrainingModuleByIDParams) (SrTrainingModules, error)
	GetSVAccessLog(ctx context.Context, arg GetSVAccessLogParams) ([]GetSVAccessLogRow, error)
	GetSVEnvProjectID(ctx context.Context, arg GetSVEnvProjectIDParams) (string, error)
	GetSVEnvironment(ctx context.Context, arg GetSVEnvironmentParams) (SoEnvironments, error)
	GetSVGitScan(ctx context.Context, arg GetSVGitScanParams) (SVGitScanRow, error)
	GetSVProject(ctx context.Context, arg GetSVProjectParams) (GetSVProjectRow, error)
	GetSVRotationPolicy(ctx context.Context, arg GetSVRotationPolicyParams) (SVRotationPolicyRow, error)
	GetSVScanResults(ctx context.Context, arg GetSVScanResultsParams) ([]SVScanResultRow, error)
	GetSVSecretByKey(ctx context.Context, arg GetSVSecretByKeyParams) (GetSVSecretByKeyRow, error)
	GetSVSecretIDByKey(ctx context.Context, arg GetSVSecretIDByKeyParams) (string, error)
	GetSVSecretProjectID(ctx context.Context, secretID string) (string, error)
	GetSVShareLink(ctx context.Context, tokenHash string) (GetSVShareLinkRow, error)
	GetSVShareLinkOrgID(ctx context.Context, id string) (string, error)
	GetUserDisplayName(ctx context.Context, id string) (string, error)
	GetUserModulePermissions(ctx context.Context, arg GetUserModulePermissionsParams) ([]UserModulePermissions, error)
	IncrementCKAuditorLinkUsage(ctx context.Context, id string) error
	// ── EU AI Act: Classifications + Documentation ─────────────────────────────
	InsertCKAIClassification(ctx context.Context, arg InsertCKAIClassificationParams) (string, error)
	InsertCKAIDocumentation(ctx context.Context, arg InsertCKAIDocumentationParams) (CkAiDocumentation, error)
	// ── CI Evidence (from Vakt Scan CI webhook) ──────────────────────────────────
	InsertCKCIEvidence(ctx context.Context, arg InsertCKCIEvidenceParams) (string, error)
	// ── Score History ───────────────────────────────────────────────────────────
	InsertCKScoreSnapshot(ctx context.Context, arg InsertCKScoreSnapshotParams) error
	InsertHRRunEvent(ctx context.Context, arg InsertHRRunEventParams) error
	// Upsert variant — duplicate (sbom_id, name, version) is a no-op (DO NOTHING).
	InsertSPComponent(ctx context.Context, arg InsertSPComponentParams) error
	// ── Access Log ──────────────────────────────────────────────────────────────
	InsertSVAccessLog(ctx context.Context, arg InsertSVAccessLogParams) error
	// ── Risk ↔ Control Links ────────────────────────────────────────────────────
	LinkCKRiskControl(ctx context.Context, arg LinkCKRiskControlParams) error
	LinkCKSupplierRisk(ctx context.Context, arg LinkCKSupplierRiskParams) error
	// Alle nicht gelöschten Organisationen (täglicher Score-Snapshot-Job).
	ListActiveOrgIDs(ctx context.Context) ([]string, error)
	ListAllBuiltinCKFrameworks(ctx context.Context) ([]CkFrameworks, error)
	ListAllCKControlExceptions(ctx context.Context, orgID string) ([]CkControlExceptions, error)
	// ── Org Helpers (verwendet von secvitals; touchen organizations/users) ────
	// Auch wenn diese Tabellen nicht unter dem ck_-Prefix laufen, gehören sie zu
	// den verschiedenen Aggregaten, die der secvitals-Service benötigt
	// (Sector-Settings, Admin-Mailings, Cross-Org-Seeding).
	ListAllOrgIDs(ctx context.Context) ([]string, error)
	ListCKAIClassifications(ctx context.Context, arg ListCKAIClassificationsParams) ([]CkAiClassifications, error)
	ListCKAIDocumentationVersions(ctx context.Context, arg ListCKAIDocumentationVersionsParams) ([]CkAiDocumentation, error)
	ListCKAISystems(ctx context.Context, arg ListCKAISystemsParams) ([]CkAiSystems, error)
	// ── EU AI Act Stats (Aggregat fürs Dashboard) ────────────────────────────
	// Minimale Projektion für GetEUAIActStats; nur risk_class + status.
	ListCKAISystemsForStats(ctx context.Context, orgID string) ([]ListCKAISystemsForStatsRow, error)
	ListCKAccessReviewCampaigns(ctx context.Context, orgID string) ([]CkAccessReviewCampaigns, error)
	ListCKAccessReviewItems(ctx context.Context, arg ListCKAccessReviewItemsParams) ([]CkAccessReviewItems, error)
	ListCKAssessmentsForSupplier(ctx context.Context, arg ListCKAssessmentsForSupplierParams) ([]CkSupplierAssessments, error)
	ListCKAuditRecords(ctx context.Context, orgID string) ([]ListCKAuditRecordsRow, error)
	ListCKAuditorLinks(ctx context.Context, orgID string) ([]ListCKAuditorLinksRow, error)
	ListCKCAPAs(ctx context.Context, arg ListCKCAPAsParams) ([]CkCapas, error)
	ListCKCAPAsForSource(ctx context.Context, arg ListCKCAPAsForSourceParams) ([]CkCapas, error)
	ListCKCAPAsPaged(ctx context.Context, arg ListCKCAPAsPagedParams) ([]CkCapas, error)
	ListCKCCMChecks(ctx context.Context, orgID string) ([]ListCKCCMChecksRow, error)
	ListCKCCMResults(ctx context.Context, arg ListCKCCMResultsParams) ([]CkCcmResults, error)
	// ── Comments ────────────────────────────────────────────────────────────────
	ListCKComments(ctx context.Context, arg ListCKCommentsParams) ([]CkComments, error)
	ListCKControlChanges(ctx context.Context, arg ListCKControlChangesParams) ([]ListCKControlChangesRow, error)
	// ── Control Exceptions (Waiver / Exception Records) ────────────────────────
	ListCKControlExceptions(ctx context.Context, arg ListCKControlExceptionsParams) ([]CkControlExceptions, error)
	// ── Control extras (Reviews + Overdue + Pagination) ───────────────────────
	ListCKControlReviews(ctx context.Context, arg ListCKControlReviewsParams) ([]ListCKControlReviewsRow, error)
	// ── Control Tasks ───────────────────────────────────────────────────────────
	ListCKControlTasks(ctx context.Context, arg ListCKControlTasksParams) ([]CkControlTasks, error)
	ListCKControls(ctx context.Context, arg ListCKControlsParams) ([]ListCKControlsRow, error)
	// SoA-Export: Controls + Evidence-Count (approved+pending) je Control.
	ListCKControlsForSoA(ctx context.Context, arg ListCKControlsForSoAParams) ([]ListCKControlsForSoARow, error)
	ListCKControlsPaged(ctx context.Context, arg ListCKControlsPagedParams) ([]ListCKControlsPagedRow, error)
	// Liefert alle aktiven Checks, die wieder dran sind:
	//   last_run_at IS NULL ODER last_run_at + interval_hours < NOW().
	ListCKDueCCMChecks(ctx context.Context) ([]ListCKDueCCMChecksRow, error)
	ListCKEvidence(ctx context.Context, arg ListCKEvidenceParams) ([]ListCKEvidenceRow, error)
	ListCKEvidenceByControls(ctx context.Context, arg ListCKEvidenceByControlsParams) ([]ListCKEvidenceByControlsRow, error)
	ListCKEvidenceFiles(ctx context.Context, arg ListCKEvidenceFilesParams) ([]CkEvidenceFiles, error)
	ListCKEvidenceFilesByControl(ctx context.Context, arg ListCKEvidenceFilesByControlParams) ([]CkEvidenceFiles, error)
	// Audit-Export: jede Control mit allen Evidence (LEFT JOIN — Controls ohne
	// Evidence erscheinen mit leeren Evidence-Feldern).
	ListCKEvidenceForFramework(ctx context.Context, arg ListCKEvidenceForFrameworkParams) ([]ListCKEvidenceForFrameworkRow, error)
	ListCKEvidenceHistory(ctx context.Context, arg ListCKEvidenceHistoryParams) ([]ListCKEvidenceHistoryRow, error)
	ListCKFrameworks(ctx context.Context, orgID string) ([]CkFrameworks, error)
	// iCal feed: open/in-progress CAPAs with due dates.
	ListCKICalCAPAs(ctx context.Context, orgID string) ([]ListCKICalCAPAsRow, error)
	// iCal feed: evidence items expiring in the future.
	ListCKICalExpiringEvidence(ctx context.Context, orgID string) ([]ListCKICalExpiringEvidenceRow, error)
	// iCal feed: upcoming audit milestones.
	ListCKICalMilestones(ctx context.Context, orgID string) ([]ListCKICalMilestonesRow, error)
	ListCKIncidentReports(ctx context.Context, arg ListCKIncidentReportsParams) ([]ListCKIncidentReportsRow, error)
	ListCKIncidents(ctx context.Context, orgID string) ([]ListCKIncidentsRow, error)
	ListCKIncidentsBySupplier(ctx context.Context, arg ListCKIncidentsBySupplierParams) ([]ListCKIncidentsBySupplierRow, error)
	ListCKIncidentsByType(ctx context.Context, arg ListCKIncidentsByTypeParams) ([]ListCKIncidentsByTypeRow, error)
	ListCKIncidentsPaged(ctx context.Context, arg ListCKIncidentsPagedParams) ([]ListCKIncidentsPagedRow, error)
	ListCKMappingsByOrg(ctx context.Context, orgID string) ([]CkFrameworkMappings, error)
	// ── Control Measures (Maßnahmen-Katalog, TISAX) ─────────────────────────────
	ListCKMeasures(ctx context.Context, arg ListCKMeasuresParams) ([]CkControlMeasures, error)
	ListCKMilestones(ctx context.Context, arg ListCKMilestonesParams) ([]ListCKMilestonesRow, error)
	ListCKMyTaskControls(ctx context.Context, arg ListCKMyTaskControlsParams) ([]ListCKMyTaskControlsRow, error)
	ListCKMyTaskRisks(ctx context.Context, arg ListCKMyTaskRisksParams) ([]ListCKMyTaskRisksRow, error)
	ListCKOverdueControls(ctx context.Context, orgID string) ([]ListCKOverdueControlsRow, error)
	ListCKOverdueTasks(ctx context.Context, orgID string) ([]CkTasks, error)
	ListCKPendingApprovals(ctx context.Context, orgID string) ([]ListCKPendingApprovalsRow, error)
	ListCKPolicies(ctx context.Context, orgID string) ([]ListCKPoliciesRow, error)
	ListCKPoliciesPaged(ctx context.Context, arg ListCKPoliciesPagedParams) ([]ListCKPoliciesPagedRow, error)
	// ── Policy Acceptance (s26-sqlc-vitals-5) ───────────────────────────────────
	ListCKPolicyAcceptanceCampaigns(ctx context.Context, arg ListCKPolicyAcceptanceCampaignsParams) ([]ListCKPolicyAcceptanceCampaignsRow, error)
	ListCKPolicyAcceptanceRequests(ctx context.Context, campaignID string) ([]ListCKPolicyAcceptanceRequestsRow, error)
	// DB-backed compliance templates from ck_policy_templates (optional category filter).
	ListCKPolicyTemplates(ctx context.Context, arg ListCKPolicyTemplatesParams) ([]ListCKPolicyTemplatesRow, error)
	// ── Policy-Versions ─────────────────────────────────────────────────────────
	ListCKPolicyVersions(ctx context.Context, arg ListCKPolicyVersionsParams) ([]CkPolicyVersions, error)
	ListCKQuestionnaires(ctx context.Context, arg ListCKQuestionnairesParams) ([]CkQuestionnaires, error)
	ListCKQuestions(ctx context.Context, questionnaireID string) ([]CkQuestionnaireQuestions, error)
	ListCKResilienceTests(ctx context.Context, orgID string) ([]CkResilienceTests, error)
	// Liefert Controls (volle Spaltenliste — consistent mit ListCKControls/GetCKControl),
	// die mit dem gegebenen Risk verknüpft sind.
	ListCKRiskControls(ctx context.Context, arg ListCKRiskControlsParams) ([]ListCKRiskControlsRow, error)
	ListCKRisks(ctx context.Context, orgID string) ([]ListCKRisksRow, error)
	ListCKRisksPaged(ctx context.Context, arg ListCKRisksPagedParams) ([]ListCKRisksPagedRow, error)
	ListCKSoAEntries(ctx context.Context, orgID string) ([]ListCKSoAEntriesRow, error)
	ListCKSupplierRisks(ctx context.Context, arg ListCKSupplierRisksParams) ([]ListCKSupplierRisksRow, error)
	ListCKSuppliers(ctx context.Context, arg ListCKSuppliersParams) ([]ListCKSuppliersRow, error)
	ListCKTasks(ctx context.Context, arg ListCKTasksParams) ([]CkTasks, error)
	// Top-10 controls for a framework by weight — used by AI policy generator for context.
	ListCKTopControlsByFramework(ctx context.Context, arg ListCKTopControlsByFrameworkParams) ([]ListCKTopControlsByFrameworkRow, error)
	ListExpiringPPAVVs(ctx context.Context, reviewDate pgtype.Date) ([]ListExpiringPPAVVsRow, error)
	ListHRChecklistRuns(ctx context.Context, arg ListHRChecklistRunsParams) ([]HrChecklistRuns, error)
	ListHRChecklists(ctx context.Context, orgID string) ([]HrChecklists, error)
	ListHREmployees(ctx context.Context, arg ListHREmployeesParams) ([]HrEmployees, error)
	ListHRRunEvents(ctx context.Context, arg ListHRRunEventsParams) ([]HrRunEvents, error)
	// ── AVV (Auftragsverarbeitungsverträge) — Art. 28 DSGVO ─────────────────────
	ListPPAVVs(ctx context.Context, orgID string) ([]ListPPAVVsRow, error)
	// ── Breaches (Datenpannen) — Art. 33/34 DSGVO ───────────────────────────────
	ListPPBreaches(ctx context.Context, orgID string) ([]PoBreaches, error)
	ListPPBreachesPaged(ctx context.Context, arg ListPPBreachesPagedParams) ([]PoBreaches, error)
	// ── DPIA (Data Protection Impact Assessment) — Art. 35 DSGVO ────────────────
	ListPPDPIAs(ctx context.Context, orgID string) ([]PoDpias, error)
	// ── DSR (Data Subject Requests) — Art. 15-21 DSGVO ──────────────────────────
	ListPPDSRs(ctx context.Context, orgID string) ([]ListPPDSRsRow, error)
	// SecPrivacy queries — sqlc migration started in v0.6.x (ADR-0005, inkrementell).
	//
	// Migrationsstand:
	//   ✅ po_vvt_entries — sqlc (this file)
	//   ✅ po_dpias       — sqlc (this file)
	//   ✅ po_avvs        — sqlc (this file)
	//   ⏳ po_breaches    — embedded SQL
	//   ⏳ po_dsr         — embedded SQL (Portal-Endpoints + DTO-Filtering)
	//
	// po_dsr ist als Letztes geplant (öffentliches Portal + DSGVO-sensitive DTO).
	// ── VVT (Verzeichnis von Verarbeitungstätigkeiten) — Art. 30 DSGVO ──────────
	ListPPVVT(ctx context.Context, orgID string) ([]PoVvtEntries, error)
	// ── Paged list helpers ──────────────────────────────────────────────────────
	ListPPVVTPaged(ctx context.Context, arg ListPPVVTPagedParams) ([]PoVvtEntries, error)
	ListSPAssets(ctx context.Context, arg ListSPAssetsParams) ([]ListSPAssetsRow, error)
	ListSPComponentsAll(ctx context.Context, arg ListSPComponentsAllParams) ([]ListSPComponentsAllRow, error)
	ListSPComponentsBySBOM(ctx context.Context, sbomID string) ([]ListSPComponentsBySBOMRow, error)
	ListSPComponentsBySBOMFull(ctx context.Context, sbomID string) ([]ListSPComponentsBySBOMFullRow, error)
	ListSPComponentsEOL(ctx context.Context, arg ListSPComponentsEOLParams) ([]ListSPComponentsEOLRow, error)
	ListSPFindingsByCreated(ctx context.Context, arg ListSPFindingsByCreatedParams) ([]VbFindings, error)
	ListSPFindingsByRisk(ctx context.Context, arg ListSPFindingsByRiskParams) ([]VbFindings, error)
	ListSPReports(ctx context.Context, orgID string) ([]ListSPReportsRow, error)
	ListSPScanSchedules(ctx context.Context, arg ListSPScanSchedulesParams) ([]VbScanSchedules, error)
	ListSPSuppressions(ctx context.Context, orgID string) ([]VbFindingSuppressions, error)
	ListSRAssignments(ctx context.Context, orgID string) ([]SrAssignments, error)
	ListSRCampaigns(ctx context.Context, orgID string) ([]ListSRCampaignsRow, error)
	ListSRCompletedAssignments(ctx context.Context, orgID string) ([]SrAssignments, error)
	ListSRLandingPages(ctx context.Context, orgID string) ([]SrLandingPages, error)
	ListSROverdueAssignments(ctx context.Context, orgID string) ([]SrAssignments, error)
	ListSRPhishReports(ctx context.Context, orgID string) ([]SrPhishReports, error)
	ListSRTargetGroups(ctx context.Context, orgID string) ([]SrTargetGroups, error)
	ListSRTargets(ctx context.Context, arg ListSRTargetsParams) ([]SrTargets, error)
	ListSRTemplates(ctx context.Context, orgID string) ([]SrTemplates, error)
	ListSRTrainingModules(ctx context.Context, orgID string) ([]SrTrainingModules, error)
	ListSVAccessLog(ctx context.Context, orgID string) ([]SoAccessLog, error)
	ListSVAPITokens(ctx context.Context, arg ListSVAPITokensParams) ([]CreateSVAPITokenRow, error)
	ListSVEnvironments(ctx context.Context, arg ListSVEnvironmentsParams) ([]SoEnvironments, error)
	ListSVGitScans(ctx context.Context, orgID string) ([]SVGitScanRow, error)
	ListSVProjectAccessLog(ctx context.Context, arg ListSVProjectAccessLogParams) ([]ListSVProjectAccessLogRow, error)
	ListSVProjectSecrets(ctx context.Context, arg ListSVProjectSecretsParams) ([]ListSVSecretKeysRow, error)
	ListSVProjects(ctx context.Context, orgID string) ([]ListSVProjectsRow, error)
	ListSVSecretKeys(ctx context.Context, arg ListSVSecretKeysParams) ([]ListSVSecretKeysRow, error)
	MarkSVShareLinkUsed(ctx context.Context, arg MarkSVShareLinkUsedParams) error
	// Setzt Assessment auf 'reviewed' und gibt supplier_id für den nachfolgenden
	// Supplier-Update zurück. Wird vom Repo in einer TX mit Update-Supplier
	// kombiniert.
	MarkCKAssessmentReviewed(ctx context.Context, arg MarkCKAssessmentReviewedParams) (string, error)
	MarkCKEvidenceExpiryNotified(ctx context.Context, dollar_1 []string) error
	// Aufrufer wählt die Deadline-Spalte über sqlc.arg('deadline'). Nur die Spalte
	// des passenden Strings wird auf NOW() gesetzt; andere bleiben unverändert.
	MarkCKIncidentDeadlineReported(ctx context.Context, arg MarkCKIncidentDeadlineReportedParams) (MarkCKIncidentDeadlineReportedRow, error)
	// Analog zu MarkDeadlineReported, aber für die Warning-Flags.
	MarkCKIncidentWarnNotified(ctx context.Context, arg MarkCKIncidentWarnNotifiedParams) error
	// Setzt sent_at für einen Akzeptanz-Request (s26-sqlc-vitals-5).
	MarkCKPolicyAcceptanceRequestSent(ctx context.Context, id string) error
	MarkExpiredPPAVVs(ctx context.Context) (int64, error)
	MarkPPBreachAuthorityNotified(ctx context.Context, arg MarkPPBreachAuthorityNotifiedParams) error
	// Returns MAX(version)+1 für die nächste Doku-Version (oder 1, wenn leer).
	NextCKAIDocumentationVersion(ctx context.Context, arg NextCKAIDocumentationVersionParams) (int32, error)
	NextCKMilestone(ctx context.Context, orgID string) (NextCKMilestoneRow, error)
	// ── Questions ───────────────────────────────────────────────────────────────
	NextCKQuestionOrderIdx(ctx context.Context, questionnaireID string) (int32, error)
	// Aufrufer iteriert die ID-Liste und ruft je Aufruf den neuen order_idx.
	ReorderCKQuestion(ctx context.Context, arg ReorderCKQuestionParams) error
	// Setzt status auf approved/rejected und gibt control_id + requested_status
	// zurück, damit der Repo-Layer optional die Control-Status-Änderung anwenden kann.
	ReviewCKApproval(ctx context.Context, arg ReviewCKApprovalParams) (ReviewCKApprovalRow, error)
	ReviewCKEvidence(ctx context.Context, arg ReviewCKEvidenceParams) (int64, error)
	RevokeCKAuditorLink(ctx context.Context, arg RevokeCKAuditorLinkParams) (int64, error)
	// Setzt accepted_at + accepted_ip; idempotent via WHERE accepted_at IS NULL (s26-sqlc-vitals-5).
	RecordCKPolicyAcceptance(ctx context.Context, arg RecordCKPolicyAcceptanceParams) (int64, error)
	SaveCKCCMResult(ctx context.Context, arg SaveCKCCMResultParams) error
	// ── Incident-Reports (PDFs) ─────────────────────────────────────────────────
	SaveCKIncidentReport(ctx context.Context, arg SaveCKIncidentReportParams) (SaveCKIncidentReportRow, error)
	// ── Cross-Framework Mappings (global reference table) ───────────────────────
	SeedCKGlobalControlMapping(ctx context.Context, arg SeedCKGlobalControlMappingParams) error
	// Idempotent (ON CONFLICT DO NOTHING). Aufrufer iteriert die Liste; jedes
	// Measure wird als is_builtin=TRUE eingefügt.
	SeedCKMeasure(ctx context.Context, arg SeedCKMeasureParams) error
	SetCKOrgApprovalRequired(ctx context.Context, arg SetCKOrgApprovalRequiredParams) (int64, error)
	SetHREmployeeStatus(ctx context.Context, arg SetHREmployeeStatusParams) error
	SetOrgPhishReportToken(ctx context.Context, arg SetOrgPhishReportTokenParams) error
	SetSRCampaignCompleted(ctx context.Context, arg SetSRCampaignCompletedParams) error
	// Snapshots the current ck_policies row into ck_policy_versions before UpdatePolicy
	// bumps version_num. ON CONFLICT (policy_id, version) DO NOTHING macht das
	// idempotent — wenn der Snapshot durch frühere Updates schon existiert,
	// bleibt er unverändert.
	SnapshotCKPolicyVersion(ctx context.Context, arg SnapshotCKPolicyVersionParams) error
	SoftDeleteSPAsset(ctx context.Context, arg SoftDeleteSPAssetParams) (int64, error)
	StartHRChecklistRun(ctx context.Context, arg StartHRChecklistRunParams) (HrChecklistRuns, error)
	StoreSPReportContent(ctx context.Context, arg StoreSPReportContentParams) error
	UnlinkCKRiskControl(ctx context.Context, arg UnlinkCKRiskControlParams) (int64, error)
	UnlinkCKSupplierRisk(ctx context.Context, arg UnlinkCKSupplierRiskParams) error
	UpdateCKAISystem(ctx context.Context, arg UpdateCKAISystemParams) (CkAiSystems, error)
	UpdateCKAISystemClassification(ctx context.Context, arg UpdateCKAISystemClassificationParams) (int64, error)
	UpdateCKAccessReviewCampaign(ctx context.Context, arg UpdateCKAccessReviewCampaignParams) (CkAccessReviewCampaigns, error)
	// decided_at wird in Go vorberechnet (only set when approving/revoking).
	UpdateCKAccessReviewItem(ctx context.Context, arg UpdateCKAccessReviewItemParams) (CkAccessReviewItems, error)
	// org_id wird via JOIN auf assessments validiert (ck_supplier_answers hat
	// keine eigene org_id-Spalte — siehe Migration 048; existierender Code
	// referenzierte sa.org_id was zur Laufzeit gefehlt hätte). Diese Variante
	// ist korrekt und multi-tenant-safe via FK-Kette.
	UpdateCKAnswerReview(ctx context.Context, arg UpdateCKAnswerReviewParams) (int64, error)
	// Submitted/reviewed sind Endzustände: einmal gesetzt, nicht mehr durch ein
	// weiteres submitted/reviewed-Update überschreibbar. Zustandsübergänge wie
	// expired→submitted oder draft→submitted bleiben weiterhin möglich.
	UpdateCKAssessmentStatus(ctx context.Context, arg UpdateCKAssessmentStatusParams) (int64, error)
	UpdateCKAuditRecord(ctx context.Context, arg UpdateCKAuditRecordParams) (UpdateCKAuditRecordRow, error)
	UpdateCKAuditorLinkAccess(ctx context.Context, id string) error
	// COALESCE-Pattern: nil-narg → behalten. Spezialregel für closed_at:
	// Bei Übergang in Status 'closed' wird closed_at = NOW() gesetzt — aber
	// nur wenn vorher noch NULL. Wechselt der Status zurück, bleibt closed_at
	// erhalten (audit-trail-Spalte).
	UpdateCKCAPA(ctx context.Context, arg UpdateCKCAPAParams) (CkCapas, error)
	UpdateCKCCMCheckEnabled(ctx context.Context, arg UpdateCKCCMCheckEnabledParams) error
	UpdateCKCCMCheckLastRun(ctx context.Context, arg UpdateCKCCMCheckLastRunParams) error
	// Partial-Update via NULL/COALESCE-Konvention:
	//   - not_applicable wird IMMER überschrieben (Bool, nicht-NULL).
	//   - reason/manual_status/owner: leerer String → NULL (NULLIF in Repo via spOptText).
	//   - maturity_score = NULL → behalten; sonst überschreiben.
	//   - due_date = NULL → behalten; sonst überschreiben.
	UpdateCKControl(ctx context.Context, arg UpdateCKControlParams) (int64, error)
	// Partial Update via COALESCE + NULLIF. approved_by hat eine Spezialregel:
	// "" wird zu NULL (explizit löschen), nil-Input behält den Wert.
	UpdateCKControlException(ctx context.Context, arg UpdateCKControlExceptionParams) (CkControlExceptions, error)
	UpdateCKControlSoAMetadata(ctx context.Context, arg UpdateCKControlSoAMetadataParams) (int64, error)
	UpdateCKControlTask(ctx context.Context, arg UpdateCKControlTaskParams) (CkControlTasks, error)
	// resolved_at-Logik:
	//   - alter Status resolved/closed → behalten
	//   - alter Status nicht, neuer ist  → NOW()
	//   - alter Status nicht, neuer auch nicht → NULL
	UpdateCKIncident(ctx context.Context, arg UpdateCKIncidentParams) (UpdateCKIncidentRow, error)
	UpdateCKIncidentReportability(ctx context.Context, arg UpdateCKIncidentReportabilityParams) error
	UpdateCKMeasure(ctx context.Context, arg UpdateCKMeasureParams) (CkControlMeasures, error)
	UpdateCKMilestone(ctx context.Context, arg UpdateCKMilestoneParams) (UpdateCKMilestoneRow, error)
	UpdateCKOrgSector(ctx context.Context, arg UpdateCKOrgSectorParams) (int64, error)
	// reviewed_at-Logik: wenn last_updated_by != '' (also Review-Aktion), → NOW();
	// sonst behalten. Logik wird im Repo entschieden und via sqlc.arg gesteuert.
	UpdateCKPolicy(ctx context.Context, arg UpdateCKPolicyParams) (UpdateCKPolicyRow, error)
	UpdateCKQuestion(ctx context.Context, arg UpdateCKQuestionParams) (CkQuestionnaireQuestions, error)
	UpdateCKQuestionnaire(ctx context.Context, arg UpdateCKQuestionnaireParams) (CkQuestionnaires, error)
	UpdateCKResilienceTest(ctx context.Context, arg UpdateCKResilienceTestParams) (CkResilienceTests, error)
	UpdateCKResilienceTestAttachment(ctx context.Context, arg UpdateCKResilienceTestAttachmentParams) (int64, error)
	UpdateCKRisk(ctx context.Context, arg UpdateCKRiskParams) (UpdateCKRiskRow, error)
	// treatment_due_date semantics: Valid=true mit Time=zero → SQL NULL ist nicht
	// ausdrückbar. Aufrufer macht read-merge-write für „keep existing" Fall —
	// nil-Input wird vorab gegen die aktuelle Zeile gemappt. Hier wird die Spalte
	// IMMER überschrieben (Valid=false → NULL, Valid=true → der Wert).
	UpdateCKRiskTreatment(ctx context.Context, arg UpdateCKRiskTreatmentParams) (UpdateCKRiskTreatmentRow, error)
	UpdateCKSoAApplicability(ctx context.Context, arg UpdateCKSoAApplicabilityParams) error
	UpdateCKSupplier(ctx context.Context, arg UpdateCKSupplierParams) (UpdateCKSupplierRow, error)
	UpdateCKSupplierAssessmentStatus(ctx context.Context, arg UpdateCKSupplierAssessmentStatusParams) error
	UpdateCKTask(ctx context.Context, arg UpdateCKTaskParams) (CkTasks, error)
	UpdateDSRPortalSettings(ctx context.Context, arg UpdateDSRPortalSettingsParams) error
	UpdateHRChecklistRun(ctx context.Context, arg UpdateHRChecklistRunParams) (HrChecklistRuns, error)
	UpdateHREmployee(ctx context.Context, arg UpdateHREmployeeParams) (HrEmployees, error)
	UpdatePPAVV(ctx context.Context, arg UpdatePPAVVParams) (UpdatePPAVVRow, error)
	UpdatePPAVVBody(ctx context.Context, arg UpdatePPAVVBodyParams) error
	UpdatePPAVVSCC(ctx context.Context, arg UpdatePPAVVSCCParams) error
	UpdatePPBreach(ctx context.Context, arg UpdatePPBreachParams) (PoBreaches, error)
	UpdatePPBreachStatus(ctx context.Context, arg UpdatePPBreachStatusParams) error
	// vvt_entry_id is intentionally not in the SET list: the link to the originating
	// VVT entry is set at creation and never re-pointed by an update — DSGVO Art. 35
	// ties a DPIA to a specific processing activity. Use Delete + Create if the
	// target activity changes.
	UpdatePPDPIA(ctx context.Context, arg UpdatePPDPIAParams) (PoDpias, error)
	UpdatePPDSR(ctx context.Context, arg UpdatePPDSRParams) (UpdatePPDSRRow, error)
	UpdatePPVVT(ctx context.Context, arg UpdatePPVVTParams) (PoVvtEntries, error)
	// Updates all fields. Callers must read-merge-write (load current asset, apply
	// partial updates from UpdateAssetInput, then pass the merged values here).
	// The dynamic SET-clause builder in the previous embedded SQL is not portable
	// to sqlc; the read-merge-write trade-off is one extra round-trip in exchange
	// for type-safe, generated code.
	UpdateSPAsset(ctx context.Context, arg UpdateSPAssetParams) (UpdateSPAssetRow, error)
	UpdateSPComponentEOL(ctx context.Context, arg UpdateSPComponentEOLParams) error
	// Partial update via COALESCE: NULL leaves the column unchanged.
	UpdateSPFinding(ctx context.Context, arg UpdateSPFindingParams) (VbFindings, error)
	UpdateSPReport(ctx context.Context, arg UpdateSPReportParams) error
	// Updates status plus any optional fields. Pass NULL via sqlc.narg() to leave
	// a column unchanged (COALESCE keeps the existing value).
	UpdateSPScanStatus(ctx context.Context, arg UpdateSPScanStatusParams) error
	UpdateSRCampaignStatus(ctx context.Context, arg UpdateSRCampaignStatusParams) error
	// ── Answers + Reviews ───────────────────────────────────────────────────────
	RevokeSVAPIToken(ctx context.Context, arg RevokeSVAPITokenParams) (int64, error)
	UpsertCKAnswer(ctx context.Context, arg UpsertCKAnswerParams) error
	UpdateSVGitScanStatus(ctx context.Context, arg UpdateSVGitScanStatusParams) error
	UpdateSVRotationAfterRotate(ctx context.Context, arg UpdateSVRotationAfterRotateParams) error
	UpdateSVSecretAccess(ctx context.Context, id string) error
	UpsertSVRotationPolicy(ctx context.Context, arg UpsertSVRotationPolicyParams) (SVRotationPolicyRow, error)
	BatchUpdateSPComponentEOL(ctx context.Context, arg BatchUpdateSPComponentEOLParams) error
	GetSPScanOrgID(ctx context.Context, id string) (string, error)
	UpsertSPEOLCache(ctx context.Context, arg UpsertSPEOLCacheParams) error
	// ── Findings Upsert (single, by raw_id) ─────────────────────────────────────
	// Single-shot INSERT...ON CONFLICT for importer flows (SARIF/CycloneDX/CSV).
	// Conflict key: (org_id, raw_id, scanner). Multi-row Upserts with conditional
	// dedup keys (cve_id vs template_id) remain procedural in the repo because
	// the conditional INSERT-vs-UPDATE branch isn't expressible in a single sqlc query.
	UpsertSPFindingByRawID(ctx context.Context, arg UpsertSPFindingByRawIDParams) (VbFindings, error)
	UpsertSPSLAConfig(ctx context.Context, arg UpsertSPSLAConfigParams) error
	// ── Assignments ───────────────────────────────────────────────────────────
	UpsertSRAssignment(ctx context.Context, arg UpsertSRAssignmentParams) (SrAssignments, error)
	UpsertSRCompletion(ctx context.Context, arg UpsertSRCompletionParams) (SrCompletions, error)
	// ── Targets ───────────────────────────────────────────────────────────────
	UpsertSRTarget(ctx context.Context, arg UpsertSRTargetParams) (SrTargets, error)
	UpsertUserModulePermission(ctx context.Context, arg UpsertUserModulePermissionParams) error
}

var _ Querier = (*Queries)(nil)
