// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secpulse.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateSPFindings = `-- name: BulkUpdateSPFindings :execrows
UPDATE vb_findings SET
  status      = COALESCE($2::text, status),
  assigned_to = COALESCE($3::uuid, assigned_to),
  updated_at  = NOW()
WHERE org_id = $1 AND id = ANY($4::uuid[])
`

type BulkUpdateSPFindingsParams struct {
	OrgID      string      `json:"org_id"`
	Status     pgtype.Text `json:"status"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
	Ids        []string    `json:"ids"`
}

// Bulk-Update über IN-Liste via UUID-Array.
func (q *Queries) BulkUpdateSPFindings(ctx context.Context, arg BulkUpdateSPFindingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateSPFindings,
		arg.OrgID,
		arg.Status,
		arg.AssignedTo,
		arg.Ids,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSPAssets = `-- name: CountSPAssets :one
SELECT COUNT(*) FROM vb_assets
WHERE org_id = $1 AND is_deleted = FALSE
  AND ($2::text IS NULL OR $2::text = ANY(tags))
`

type CountSPAssetsParams struct {
	OrgID string      `json:"org_id"`
	Tag   pgtype.Text `json:"tag"`
}

func (q *Queries) CountSPAssets(ctx context.Context, arg CountSPAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSPAssets, arg.OrgID, arg.Tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSPFindings = `-- name: CountSPFindings :one
SELECT COUNT(*) FROM vb_findings
WHERE org_id = $1
  AND ($2::text IS NULL OR severity = $2::text)
  AND ($3::text   IS NULL OR status   = $3::text)
  AND ($4::uuid IS NULL OR asset_id = $4::uuid)
`

type CountSPFindingsParams struct {
	OrgID    string      `json:"org_id"`
	Severity pgtype.Text `json:"severity"`
	Status   pgtype.Text `json:"status"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) CountSPFindings(ctx context.Context, arg CountSPFindingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSPFindings,
		arg.OrgID,
		arg.Severity,
		arg.Status,
		arg.AssetID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSPAsset = `-- name: CreateSPAsset :one


INSERT INTO vb_assets (org_id, name, type, criticality, tags, owner_id, external_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, name, type, criticality, tags, owner_id, external_url,
          created_at, updated_at
`

type CreateSPAssetParams struct {
	OrgID       string      `json:"org_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Criticality string      `json:"criticality"`
	Tags        []string    `json:"tags"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	ExternalUrl pgtype.Text `json:"external_url"`
}

type CreateSPAssetRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Criticality string             `json:"criticality"`
	Tags        []string           `json:"tags"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Vakt Scan queries — sqlc migration in v0.6.x (ADR-0005).
//
// Migrationsstand:
//
//	✅ vb_assets     — sqlc (this file)
//	✅ vb_sla_config — sqlc
//	✅ vb_scans      — sqlc
//	⏳ vb_findings   — embedded SQL (Sitzung C2 — Dedup-Logik)
//	⏳ vb_components / vb_sboms / vb_reports / vb_finding_suppressions /
//	   vb_scan_schedules / vb_eol_cache — embedded SQL (Sitzung C3)
//
// ── Assets ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateSPAsset(ctx context.Context, arg CreateSPAssetParams) (CreateSPAssetRow, error) {
	row := q.db.QueryRow(ctx, createSPAsset,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Criticality,
		arg.Tags,
		arg.OwnerID,
		arg.ExternalUrl,
	)
	var i CreateSPAssetRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Criticality,
		&i.Tags,
		&i.OwnerID,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSPReport = `-- name: CreateSPReport :one

INSERT INTO vb_reports (org_id, generated_by, scope, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, org_id, generated_by, scope, file_path, status, expires_at, created_at
`

type CreateSPReportParams struct {
	OrgID       string          `json:"org_id"`
	GeneratedBy pgtype.UUID     `json:"generated_by"`
	Scope       json.RawMessage `json:"scope"`
}

type CreateSPReportRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	GeneratedBy pgtype.UUID        `json:"generated_by"`
	Scope       json.RawMessage    `json:"scope"`
	FilePath    pgtype.Text        `json:"file_path"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// ── Reports ─────────────────────────────────────────────────────────────────
func (q *Queries) CreateSPReport(ctx context.Context, arg CreateSPReportParams) (CreateSPReportRow, error) {
	row := q.db.QueryRow(ctx, createSPReport, arg.OrgID, arg.GeneratedBy, arg.Scope)
	var i CreateSPReportRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GeneratedBy,
		&i.Scope,
		&i.FilePath,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSPSBOM = `-- name: CreateSPSBOM :one

INSERT INTO vb_sboms (org_id, asset_id, format, spec_version, document, component_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateSPSBOMParams struct {
	OrgID          string          `json:"org_id"`
	AssetID        string          `json:"asset_id"`
	Format         string          `json:"format"`
	SpecVersion    string          `json:"spec_version"`
	Document       json.RawMessage `json:"document"`
	ComponentCount int32           `json:"component_count"`
}

// ── SBOM ────────────────────────────────────────────────────────────────────
func (q *Queries) CreateSPSBOM(ctx context.Context, arg CreateSPSBOMParams) (string, error) {
	row := q.db.QueryRow(ctx, createSPSBOM,
		arg.OrgID,
		arg.AssetID,
		arg.Format,
		arg.SpecVersion,
		arg.Document,
		arg.ComponentCount,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createSPScan = `-- name: CreateSPScan :one

INSERT INTO vb_scans (org_id, asset_id, scanner, status, target_url, target_ip)
VALUES ($1, $2, $3, 'pending', $4, $5)
RETURNING id, org_id, asset_id, scanner, status,
          target_url, target_ip, error_message, finding_count,
          duration_ms, started_at, completed_at, created_at
`

type CreateSPScanParams struct {
	OrgID     string      `json:"org_id"`
	AssetID   string      `json:"asset_id"`
	Scanner   string      `json:"scanner"`
	TargetUrl pgtype.Text `json:"target_url"`
	TargetIp  pgtype.Text `json:"target_ip"`
}

// ── Scans ───────────────────────────────────────────────────────────────────
func (q *Queries) CreateSPScan(ctx context.Context, arg CreateSPScanParams) (VbScans, error) {
	row := q.db.QueryRow(ctx, createSPScan,
		arg.OrgID,
		arg.AssetID,
		arg.Scanner,
		arg.TargetUrl,
		arg.TargetIp,
	)
	var i VbScans
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetID,
		&i.Scanner,
		&i.Status,
		&i.TargetUrl,
		&i.TargetIp,
		&i.ErrorMessage,
		&i.FindingCount,
		&i.DurationMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSPScanSchedule = `-- name: CreateSPScanSchedule :one

INSERT INTO vb_scan_schedules (org_id, asset_id, scanner, cron_expr, is_active)
VALUES ($1, $2, $3, $4, TRUE)
RETURNING id, org_id, asset_id, scanner, cron_expr, is_active,
          last_run, next_run, created_at
`

type CreateSPScanScheduleParams struct {
	OrgID    string `json:"org_id"`
	AssetID  string `json:"asset_id"`
	Scanner  string `json:"scanner"`
	CronExpr string `json:"cron_expr"`
}

// ── Scan Schedules ──────────────────────────────────────────────────────────
func (q *Queries) CreateSPScanSchedule(ctx context.Context, arg CreateSPScanScheduleParams) (VbScanSchedules, error) {
	row := q.db.QueryRow(ctx, createSPScanSchedule,
		arg.OrgID,
		arg.AssetID,
		arg.Scanner,
		arg.CronExpr,
	)
	var i VbScanSchedules
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetID,
		&i.Scanner,
		&i.CronExpr,
		&i.IsActive,
		&i.LastRun,
		&i.NextRun,
		&i.CreatedAt,
	)
	return i, err
}

const createSPSuppression = `-- name: CreateSPSuppression :one

INSERT INTO vb_finding_suppressions (org_id, cve_id, asset_tag, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, cve_id, asset_tag, reason, created_by, match_count, created_at
`

type CreateSPSuppressionParams struct {
	OrgID     string      `json:"org_id"`
	CveID     pgtype.Text `json:"cve_id"`
	AssetTag  pgtype.Text `json:"asset_tag"`
	Reason    string      `json:"reason"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

// ── Suppression Rules ───────────────────────────────────────────────────────
func (q *Queries) CreateSPSuppression(ctx context.Context, arg CreateSPSuppressionParams) (VbFindingSuppressions, error) {
	row := q.db.QueryRow(ctx, createSPSuppression,
		arg.OrgID,
		arg.CveID,
		arg.AssetTag,
		arg.Reason,
		arg.CreatedBy,
	)
	var i VbFindingSuppressions
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CveID,
		&i.AssetTag,
		&i.Reason,
		&i.CreatedBy,
		&i.MatchCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSPScanSchedule = `-- name: DeleteSPScanSchedule :execrows
DELETE FROM vb_scan_schedules
WHERE id = $1 AND org_id = $2
`

type DeleteSPScanScheduleParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteSPScanSchedule(ctx context.Context, arg DeleteSPScanScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSPScanSchedule, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSPSuppression = `-- name: DeleteSPSuppression :execrows
DELETE FROM vb_finding_suppressions
WHERE id = $1 AND org_id = $2
`

type DeleteSPSuppressionParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteSPSuppression(ctx context.Context, arg DeleteSPSuppressionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSPSuppression, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestSPSBOM = `-- name: GetLatestSPSBOM :one
SELECT id, asset_id, format, component_count, created_at
FROM vb_sboms
WHERE org_id = $1 AND asset_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSPSBOMParams struct {
	OrgID   string `json:"org_id"`
	AssetID string `json:"asset_id"`
}

type GetLatestSPSBOMRow struct {
	ID             string             `json:"id"`
	AssetID        string             `json:"asset_id"`
	Format         string             `json:"format"`
	ComponentCount int32              `json:"component_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestSPSBOM(ctx context.Context, arg GetLatestSPSBOMParams) (GetLatestSPSBOMRow, error) {
	row := q.db.QueryRow(ctx, getLatestSPSBOM, arg.OrgID, arg.AssetID)
	var i GetLatestSPSBOMRow
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Format,
		&i.ComponentCount,
		&i.CreatedAt,
	)
	return i, err
}

const getSPAsset = `-- name: GetSPAsset :one
SELECT id, org_id, name, type, criticality, tags, owner_id, external_url,
       created_at, updated_at
FROM vb_assets
WHERE id = $1 AND org_id = $2 AND is_deleted = FALSE
`

type GetSPAssetParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetSPAssetRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Criticality string             `json:"criticality"`
	Tags        []string           `json:"tags"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSPAsset(ctx context.Context, arg GetSPAssetParams) (GetSPAssetRow, error) {
	row := q.db.QueryRow(ctx, getSPAsset, arg.ID, arg.OrgID)
	var i GetSPAssetRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Criticality,
		&i.Tags,
		&i.OwnerID,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSPAssetByName = `-- name: GetSPAssetByName :one
SELECT id, org_id, name, type, criticality, tags, owner_id, external_url,
       created_at, updated_at
FROM vb_assets
WHERE org_id = $1 AND lower(name) = lower($2::text) AND is_deleted = FALSE
LIMIT 1
`

type GetSPAssetByNameParams struct {
	OrgID   string `json:"org_id"`
	Column2 string `json:"column_2"`
}

type GetSPAssetByNameRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Criticality string             `json:"criticality"`
	Tags        []string           `json:"tags"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSPAssetByName(ctx context.Context, arg GetSPAssetByNameParams) (GetSPAssetByNameRow, error) {
	row := q.db.QueryRow(ctx, getSPAssetByName, arg.OrgID, arg.Column2)
	var i GetSPAssetByNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Criticality,
		&i.Tags,
		&i.OwnerID,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSPEOLCache = `-- name: GetSPEOLCache :one

SELECT payload, fetched_at
FROM vb_eol_cache
WHERE product = $1 AND cycle = $2
`

type GetSPEOLCacheParams struct {
	Product string `json:"product"`
	Cycle   string `json:"cycle"`
}

type GetSPEOLCacheRow struct {
	Payload   []byte             `json:"payload"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

// ── EOL Cache ───────────────────────────────────────────────────────────────
func (q *Queries) GetSPEOLCache(ctx context.Context, arg GetSPEOLCacheParams) (GetSPEOLCacheRow, error) {
	row := q.db.QueryRow(ctx, getSPEOLCache, arg.Product, arg.Cycle)
	var i GetSPEOLCacheRow
	err := row.Scan(&i.Payload, &i.FetchedAt)
	return i, err
}

const getSPFinding = `-- name: GetSPFinding :one

SELECT id, org_id, asset_id, scan_id, cve_id,
       title, description, severity,
       cvss_score, epss_score, epss_percentile, risk_score,
       status, scanner, raw_id, sources, template_id,
       assigned_to, justification,
       reopen_count, occurrence_count,
       last_seen_at, sla_due_at, created_at, updated_at
FROM vb_findings
WHERE id = $1 AND org_id = $2
`

type GetSPFindingParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

// ── Findings (Read + Update) ────────────────────────────────────────────────
// Upsert/Dedup queries (UpsertFinding, BatchUpsertFindings) remain embedded for
// now — their business logic (cve_id vs template_id dedup, reopen_count rules,
// source-set merge) is hard to express as a single sqlc query and currently
// sits in the repository (Sitzung C2b).
func (q *Queries) GetSPFinding(ctx context.Context, arg GetSPFindingParams) (VbFindings, error) {
	row := q.db.QueryRow(ctx, getSPFinding, arg.ID, arg.OrgID)
	var i VbFindings
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetID,
		&i.ScanID,
		&i.CveID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssScore,
		&i.EpssScore,
		&i.EpssPercentile,
		&i.RiskScore,
		&i.Status,
		&i.Scanner,
		&i.RawID,
		&i.Sources,
		&i.TemplateID,
		&i.AssignedTo,
		&i.Justification,
		&i.ReopenCount,
		&i.OccurrenceCount,
		&i.LastSeenAt,
		&i.SlaDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSPReport = `-- name: GetSPReport :one
SELECT id, org_id, generated_by, scope, file_path, status, expires_at, created_at
FROM vb_reports
WHERE id = $1 AND org_id = $2
`

type GetSPReportParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetSPReportRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	GeneratedBy pgtype.UUID        `json:"generated_by"`
	Scope       json.RawMessage    `json:"scope"`
	FilePath    pgtype.Text        `json:"file_path"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSPReport(ctx context.Context, arg GetSPReportParams) (GetSPReportRow, error) {
	row := q.db.QueryRow(ctx, getSPReport, arg.ID, arg.OrgID)
	var i GetSPReportRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GeneratedBy,
		&i.Scope,
		&i.FilePath,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSPReportContent = `-- name: GetSPReportContent :one
SELECT content, scope FROM vb_reports
WHERE id = $1 AND org_id = $2 AND status = 'completed'
`

type GetSPReportContentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetSPReportContentRow struct {
	Content []byte          `json:"content"`
	Scope   json.RawMessage `json:"scope"`
}

func (q *Queries) GetSPReportContent(ctx context.Context, arg GetSPReportContentParams) (GetSPReportContentRow, error) {
	row := q.db.QueryRow(ctx, getSPReportContent, arg.ID, arg.OrgID)
	var i GetSPReportContentRow
	err := row.Scan(&i.Content, &i.Scope)
	return i, err
}

const getSPRiskTrend = `-- name: GetSPRiskTrend :many

SELECT
    TO_CHAR(d::date, 'YYYY-MM-DD')                 AS date,
    COALESCE(SUM(f.risk_score), 0)::float8         AS total_risk_score,
    COUNT(f.id)::int                                AS open_count,
    COUNT(f.id) FILTER (WHERE f.severity = 'critical')::int AS critical_count
FROM generate_series(
    (NOW() - make_interval(days => $2::int))::date,
    NOW()::date,
    '1 day'::interval
) AS d
LEFT JOIN vb_findings f
    ON f.org_id = $1
   AND f.status = 'open'
   AND f.created_at < (d::date + INTERVAL '1 day')
GROUP BY d
ORDER BY d
`

type GetSPRiskTrendParams struct {
	OrgID   string `json:"org_id"`
	Column2 int32  `json:"column_2"`
}

type GetSPRiskTrendRow struct {
	Date           string  `json:"date"`
	TotalRiskScore float64 `json:"total_risk_score"`
	OpenCount      int32   `json:"open_count"`
	CriticalCount  int32   `json:"critical_count"`
}

// ── Risk Trend ──────────────────────────────────────────────────────────────
// Aggregates open findings per day for the last :days days.
func (q *Queries) GetSPRiskTrend(ctx context.Context, arg GetSPRiskTrendParams) ([]GetSPRiskTrendRow, error) {
	rows, err := q.db.Query(ctx, getSPRiskTrend, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSPRiskTrendRow{}
	for rows.Next() {
		var i GetSPRiskTrendRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalRiskScore,
			&i.OpenCount,
			&i.CriticalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSPSLAConfig = `-- name: GetSPSLAConfig :one

SELECT org_id, critical_days, high_days, medium_days, low_days
FROM vb_sla_config
WHERE org_id = $1
`

type GetSPSLAConfigRow struct {
	OrgID        string `json:"org_id"`
	CriticalDays int32  `json:"critical_days"`
	HighDays     int32  `json:"high_days"`
	MediumDays   int32  `json:"medium_days"`
	LowDays      int32  `json:"low_days"`
}

// ── SLA-Config ──────────────────────────────────────────────────────────────
func (q *Queries) GetSPSLAConfig(ctx context.Context, orgID string) (GetSPSLAConfigRow, error) {
	row := q.db.QueryRow(ctx, getSPSLAConfig, orgID)
	var i GetSPSLAConfigRow
	err := row.Scan(
		&i.OrgID,
		&i.CriticalDays,
		&i.HighDays,
		&i.MediumDays,
		&i.LowDays,
	)
	return i, err
}

const getSPSLADashboard = `-- name: GetSPSLADashboard :many
SELECT
    a.id           AS asset_id,
    a.name         AS asset_name,
    f.id           AS finding_id,
    f.title        AS finding_title,
    f.severity,
    f.status,
    EXTRACT(DAY FROM now() - f.created_at)::int AS days_open
FROM vb_findings f
JOIN vb_assets a ON a.id = f.asset_id
WHERE f.org_id = $1
  AND f.status NOT IN ('resolved', 'false_positive')
ORDER BY f.severity DESC, days_open DESC
LIMIT 100
`

type GetSPSLADashboardRow struct {
	AssetID      string `json:"asset_id"`
	AssetName    string `json:"asset_name"`
	FindingID    string `json:"finding_id"`
	FindingTitle string `json:"finding_title"`
	Severity     string `json:"severity"`
	Status       string `json:"status"`
	DaysOpen     int32  `json:"days_open"`
}

func (q *Queries) GetSPSLADashboard(ctx context.Context, orgID string) ([]GetSPSLADashboardRow, error) {
	rows, err := q.db.Query(ctx, getSPSLADashboard, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSPSLADashboardRow{}
	for rows.Next() {
		var i GetSPSLADashboardRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AssetName,
			&i.FindingID,
			&i.FindingTitle,
			&i.Severity,
			&i.Status,
			&i.DaysOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSPScan = `-- name: GetSPScan :one
SELECT id, org_id, asset_id, scanner, status,
       target_url, target_ip, error_message, finding_count,
       duration_ms, started_at, completed_at, created_at
FROM vb_scans
WHERE id = $1 AND org_id = $2
`

type GetSPScanParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSPScan(ctx context.Context, arg GetSPScanParams) (VbScans, error) {
	row := q.db.QueryRow(ctx, getSPScan, arg.ID, arg.OrgID)
	var i VbScans
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetID,
		&i.Scanner,
		&i.Status,
		&i.TargetUrl,
		&i.TargetIp,
		&i.ErrorMessage,
		&i.FindingCount,
		&i.DurationMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertSPComponent = `-- name: InsertSPComponent :exec
INSERT INTO vb_components (org_id, sbom_id, name, version, purl)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sbom_id, name, version) DO NOTHING
`

type InsertSPComponentParams struct {
	OrgID   string      `json:"org_id"`
	SbomID  string      `json:"sbom_id"`
	Name    string      `json:"name"`
	Version string      `json:"version"`
	Purl    pgtype.Text `json:"purl"`
}

// Upsert variant — duplicate (sbom_id, name, version) is a no-op (DO NOTHING).
func (q *Queries) InsertSPComponent(ctx context.Context, arg InsertSPComponentParams) error {
	_, err := q.db.Exec(ctx, insertSPComponent,
		arg.OrgID,
		arg.SbomID,
		arg.Name,
		arg.Version,
		arg.Purl,
	)
	return err
}

const listSPAssets = `-- name: ListSPAssets :many
SELECT id, org_id, name, type, criticality, tags, owner_id, external_url,
       created_at, updated_at
FROM vb_assets
WHERE org_id = $1 AND is_deleted = FALSE
  AND ($4::text IS NULL OR $4::text = ANY(tags))
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSPAssetsParams struct {
	OrgID  string      `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Tag    pgtype.Text `json:"tag"`
}

type ListSPAssetsRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Criticality string             `json:"criticality"`
	Tags        []string           `json:"tags"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSPAssets(ctx context.Context, arg ListSPAssetsParams) ([]ListSPAssetsRow, error) {
	rows, err := q.db.Query(ctx, listSPAssets,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Tag,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSPAssetsRow{}
	for rows.Next() {
		var i ListSPAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.Criticality,
			&i.Tags,
			&i.OwnerID,
			&i.ExternalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPComponentsAll = `-- name: ListSPComponentsAll :many
SELECT c.id, c.name, c.version, c.purl, c.eol_status, c.eol_date, s.asset_id
FROM vb_components c
JOIN vb_sboms s ON s.id = c.sbom_id
WHERE c.org_id = $1
ORDER BY c.name, c.version
LIMIT $2 OFFSET $3
`

type ListSPComponentsAllParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListSPComponentsAllRow struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Version   string      `json:"version"`
	Purl      pgtype.Text `json:"purl"`
	EolStatus string      `json:"eol_status"`
	EolDate   pgtype.Date `json:"eol_date"`
	AssetID   string      `json:"asset_id"`
}

func (q *Queries) ListSPComponentsAll(ctx context.Context, arg ListSPComponentsAllParams) ([]ListSPComponentsAllRow, error) {
	rows, err := q.db.Query(ctx, listSPComponentsAll, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSPComponentsAllRow{}
	for rows.Next() {
		var i ListSPComponentsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Purl,
			&i.EolStatus,
			&i.EolDate,
			&i.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPComponentsBySBOM = `-- name: ListSPComponentsBySBOM :many
SELECT id, name, version
FROM vb_components
WHERE sbom_id = $1
LIMIT 10000
`

type ListSPComponentsBySBOMRow struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) ListSPComponentsBySBOM(ctx context.Context, sbomID string) ([]ListSPComponentsBySBOMRow, error) {
	rows, err := q.db.Query(ctx, listSPComponentsBySBOM, sbomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSPComponentsBySBOMRow{}
	for rows.Next() {
		var i ListSPComponentsBySBOMRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPComponentsEOL = `-- name: ListSPComponentsEOL :many
SELECT c.id, c.name, c.version, c.purl, c.eol_status, c.eol_date, s.asset_id
FROM vb_components c
JOIN vb_sboms s ON s.id = c.sbom_id
WHERE c.org_id = $1 AND c.eol_status = 'eol'
ORDER BY c.name, c.version
LIMIT $2 OFFSET $3
`

type ListSPComponentsEOLParams struct {
	OrgID  string `json:"org_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListSPComponentsEOLRow struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Version   string      `json:"version"`
	Purl      pgtype.Text `json:"purl"`
	EolStatus string      `json:"eol_status"`
	EolDate   pgtype.Date `json:"eol_date"`
	AssetID   string      `json:"asset_id"`
}

func (q *Queries) ListSPComponentsEOL(ctx context.Context, arg ListSPComponentsEOLParams) ([]ListSPComponentsEOLRow, error) {
	rows, err := q.db.Query(ctx, listSPComponentsEOL, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSPComponentsEOLRow{}
	for rows.Next() {
		var i ListSPComponentsEOLRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Purl,
			&i.EolStatus,
			&i.EolDate,
			&i.AssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPFindingsByCreated = `-- name: ListSPFindingsByCreated :many
SELECT id, org_id, asset_id, scan_id, cve_id,
       title, description, severity,
       cvss_score, epss_score, epss_percentile, risk_score,
       status, scanner, raw_id, sources, template_id,
       assigned_to, justification,
       reopen_count, occurrence_count,
       last_seen_at, sla_due_at, created_at, updated_at
FROM vb_findings
WHERE org_id = $1
  AND ($4::text IS NULL OR severity = $4::text)
  AND ($5::text   IS NULL OR status   = $5::text)
  AND ($6::uuid IS NULL OR asset_id = $6::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSPFindingsByCreatedParams struct {
	OrgID    string      `json:"org_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Severity pgtype.Text `json:"severity"`
	Status   pgtype.Text `json:"status"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) ListSPFindingsByCreated(ctx context.Context, arg ListSPFindingsByCreatedParams) ([]VbFindings, error) {
	rows, err := q.db.Query(ctx, listSPFindingsByCreated,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Severity,
		arg.Status,
		arg.AssetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VbFindings{}
	for rows.Next() {
		var i VbFindings
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AssetID,
			&i.ScanID,
			&i.CveID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssScore,
			&i.EpssScore,
			&i.EpssPercentile,
			&i.RiskScore,
			&i.Status,
			&i.Scanner,
			&i.RawID,
			&i.Sources,
			&i.TemplateID,
			&i.AssignedTo,
			&i.Justification,
			&i.ReopenCount,
			&i.OccurrenceCount,
			&i.LastSeenAt,
			&i.SlaDueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPFindingsByRisk = `-- name: ListSPFindingsByRisk :many
SELECT id, org_id, asset_id, scan_id, cve_id,
       title, description, severity,
       cvss_score, epss_score, epss_percentile, risk_score,
       status, scanner, raw_id, sources, template_id,
       assigned_to, justification,
       reopen_count, occurrence_count,
       last_seen_at, sla_due_at, created_at, updated_at
FROM vb_findings
WHERE org_id = $1
  AND ($4::text IS NULL OR severity = $4::text)
  AND ($5::text   IS NULL OR status   = $5::text)
  AND ($6::uuid IS NULL OR asset_id = $6::uuid)
ORDER BY risk_score DESC NULLS LAST, created_at DESC
LIMIT $2 OFFSET $3
`

type ListSPFindingsByRiskParams struct {
	OrgID    string      `json:"org_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Severity pgtype.Text `json:"severity"`
	Status   pgtype.Text `json:"status"`
	AssetID  pgtype.UUID `json:"asset_id"`
}

func (q *Queries) ListSPFindingsByRisk(ctx context.Context, arg ListSPFindingsByRiskParams) ([]VbFindings, error) {
	rows, err := q.db.Query(ctx, listSPFindingsByRisk,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.Severity,
		arg.Status,
		arg.AssetID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VbFindings{}
	for rows.Next() {
		var i VbFindings
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AssetID,
			&i.ScanID,
			&i.CveID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.CvssScore,
			&i.EpssScore,
			&i.EpssPercentile,
			&i.RiskScore,
			&i.Status,
			&i.Scanner,
			&i.RawID,
			&i.Sources,
			&i.TemplateID,
			&i.AssignedTo,
			&i.Justification,
			&i.ReopenCount,
			&i.OccurrenceCount,
			&i.LastSeenAt,
			&i.SlaDueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPReports = `-- name: ListSPReports :many
SELECT id, org_id, generated_by, scope, file_path, status, expires_at, created_at
FROM vb_reports
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListSPReportsRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	GeneratedBy pgtype.UUID        `json:"generated_by"`
	Scope       json.RawMessage    `json:"scope"`
	FilePath    pgtype.Text        `json:"file_path"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSPReports(ctx context.Context, orgID string) ([]ListSPReportsRow, error) {
	rows, err := q.db.Query(ctx, listSPReports, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSPReportsRow{}
	for rows.Next() {
		var i ListSPReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GeneratedBy,
			&i.Scope,
			&i.FilePath,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPScanSchedules = `-- name: ListSPScanSchedules :many
SELECT id, org_id, asset_id, scanner, cron_expr, is_active,
       last_run, next_run, created_at
FROM vb_scan_schedules
WHERE org_id = $1 AND asset_id = $2
ORDER BY created_at DESC
LIMIT 500
`

type ListSPScanSchedulesParams struct {
	OrgID   string `json:"org_id"`
	AssetID string `json:"asset_id"`
}

func (q *Queries) ListSPScanSchedules(ctx context.Context, arg ListSPScanSchedulesParams) ([]VbScanSchedules, error) {
	rows, err := q.db.Query(ctx, listSPScanSchedules, arg.OrgID, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VbScanSchedules{}
	for rows.Next() {
		var i VbScanSchedules
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AssetID,
			&i.Scanner,
			&i.CronExpr,
			&i.IsActive,
			&i.LastRun,
			&i.NextRun,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSPSuppressions = `-- name: ListSPSuppressions :many
SELECT id, org_id, cve_id, asset_tag, reason, created_by, match_count, created_at
FROM vb_finding_suppressions
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT 10000
`

func (q *Queries) ListSPSuppressions(ctx context.Context, orgID string) ([]VbFindingSuppressions, error) {
	rows, err := q.db.Query(ctx, listSPSuppressions, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VbFindingSuppressions{}
	for rows.Next() {
		var i VbFindingSuppressions
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CveID,
			&i.AssetTag,
			&i.Reason,
			&i.CreatedBy,
			&i.MatchCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSPAsset = `-- name: SoftDeleteSPAsset :execrows
UPDATE vb_assets SET is_deleted = TRUE, updated_at = NOW()
WHERE id = $1 AND org_id = $2 AND is_deleted = FALSE
`

type SoftDeleteSPAssetParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) SoftDeleteSPAsset(ctx context.Context, arg SoftDeleteSPAssetParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSPAsset, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeSPReportContent = `-- name: StoreSPReportContent :exec
UPDATE vb_reports
SET content = $2, status = 'completed', expires_at = $3, file_path = ''
WHERE id = $1
`

type StoreSPReportContentParams struct {
	ID        string             `json:"id"`
	Content   []byte             `json:"content"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) StoreSPReportContent(ctx context.Context, arg StoreSPReportContentParams) error {
	_, err := q.db.Exec(ctx, storeSPReportContent, arg.ID, arg.Content, arg.ExpiresAt)
	return err
}

const updateSPAsset = `-- name: UpdateSPAsset :one
UPDATE vb_assets SET
  name         = $3,
  type         = $4,
  criticality  = $5,
  tags         = $6,
  owner_id     = $7,
  external_url = $8,
  updated_at   = NOW()
WHERE id = $1 AND org_id = $2 AND is_deleted = FALSE
RETURNING id, org_id, name, type, criticality, tags, owner_id, external_url,
          created_at, updated_at
`

type UpdateSPAssetParams struct {
	ID          string      `json:"id"`
	OrgID       string      `json:"org_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Criticality string      `json:"criticality"`
	Tags        []string    `json:"tags"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	ExternalUrl pgtype.Text `json:"external_url"`
}

type UpdateSPAssetRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Criticality string             `json:"criticality"`
	Tags        []string           `json:"tags"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	ExternalUrl pgtype.Text        `json:"external_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Updates all fields. Callers must read-merge-write (load current asset, apply
// partial updates from UpdateAssetInput, then pass the merged values here).
// The dynamic SET-clause builder in the previous embedded SQL is not portable
// to sqlc; the read-merge-write trade-off is one extra round-trip in exchange
// for type-safe, generated code.
func (q *Queries) UpdateSPAsset(ctx context.Context, arg UpdateSPAssetParams) (UpdateSPAssetRow, error) {
	row := q.db.QueryRow(ctx, updateSPAsset,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Criticality,
		arg.Tags,
		arg.OwnerID,
		arg.ExternalUrl,
	)
	var i UpdateSPAssetRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Criticality,
		&i.Tags,
		&i.OwnerID,
		&i.ExternalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSPComponentEOL = `-- name: UpdateSPComponentEOL :exec
UPDATE vb_components
SET eol_status     = $2,
    eol_date       = $3::date,
    eol_checked_at = NOW()
WHERE id = $1
`

type UpdateSPComponentEOLParams struct {
	ID        string      `json:"id"`
	EolStatus string      `json:"eol_status"`
	EolDate   pgtype.Date `json:"eol_date"`
}

func (q *Queries) UpdateSPComponentEOL(ctx context.Context, arg UpdateSPComponentEOLParams) error {
	_, err := q.db.Exec(ctx, updateSPComponentEOL, arg.ID, arg.EolStatus, arg.EolDate)
	return err
}

const updateSPFinding = `-- name: UpdateSPFinding :one
UPDATE vb_findings SET
  status        = COALESCE($3::text, status),
  assigned_to   = COALESCE($4::uuid, assigned_to),
  justification = COALESCE($5::text, justification),
  severity      = COALESCE($6::text, severity),
  updated_at    = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, asset_id, scan_id, cve_id,
          title, description, severity,
          cvss_score, epss_score, epss_percentile, risk_score,
          status, scanner, raw_id, sources, template_id,
          assigned_to, justification,
          reopen_count, occurrence_count,
          last_seen_at, sla_due_at, created_at, updated_at
`

type UpdateSPFindingParams struct {
	ID            string      `json:"id"`
	OrgID         string      `json:"org_id"`
	Status        pgtype.Text `json:"status"`
	AssignedTo    pgtype.UUID `json:"assigned_to"`
	Justification pgtype.Text `json:"justification"`
	Severity      pgtype.Text `json:"severity"`
}

// Partial update via COALESCE: NULL leaves the column unchanged.
func (q *Queries) UpdateSPFinding(ctx context.Context, arg UpdateSPFindingParams) (VbFindings, error) {
	row := q.db.QueryRow(ctx, updateSPFinding,
		arg.ID,
		arg.OrgID,
		arg.Status,
		arg.AssignedTo,
		arg.Justification,
		arg.Severity,
	)
	var i VbFindings
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetID,
		&i.ScanID,
		&i.CveID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssScore,
		&i.EpssScore,
		&i.EpssPercentile,
		&i.RiskScore,
		&i.Status,
		&i.Scanner,
		&i.RawID,
		&i.Sources,
		&i.TemplateID,
		&i.AssignedTo,
		&i.Justification,
		&i.ReopenCount,
		&i.OccurrenceCount,
		&i.LastSeenAt,
		&i.SlaDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSPReport = `-- name: UpdateSPReport :exec
UPDATE vb_reports
SET file_path = $2, status = $3, expires_at = $4
WHERE id = $1
`

type UpdateSPReportParams struct {
	ID        string             `json:"id"`
	FilePath  pgtype.Text        `json:"file_path"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSPReport(ctx context.Context, arg UpdateSPReportParams) error {
	_, err := q.db.Exec(ctx, updateSPReport,
		arg.ID,
		arg.FilePath,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}

const updateSPScanStatus = `-- name: UpdateSPScanStatus :exec
UPDATE vb_scans SET
  status        = $2,
  error_message = COALESCE($3::text, error_message),
  finding_count = COALESCE($4::int, finding_count),
  duration_ms   = COALESCE($5::bigint, duration_ms),
  started_at    = COALESCE($6::timestamptz, started_at),
  completed_at  = COALESCE($7::timestamptz, completed_at)
WHERE id = $1
`

type UpdateSPScanStatusParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	FindingCount pgtype.Int4        `json:"finding_count"`
	DurationMs   pgtype.Int8        `json:"duration_ms"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

// Updates status plus any optional fields. Pass NULL via sqlc.narg() to leave
// a column unchanged (COALESCE keeps the existing value).
func (q *Queries) UpdateSPScanStatus(ctx context.Context, arg UpdateSPScanStatusParams) error {
	_, err := q.db.Exec(ctx, updateSPScanStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.FindingCount,
		arg.DurationMs,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const upsertSPEOLCache = `-- name: UpsertSPEOLCache :exec
INSERT INTO vb_eol_cache (product, cycle, payload, fetched_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (product, cycle) DO UPDATE
  SET payload    = EXCLUDED.payload,
      fetched_at = EXCLUDED.fetched_at
`

type UpsertSPEOLCacheParams struct {
	Product string `json:"product"`
	Cycle   string `json:"cycle"`
	Payload []byte `json:"payload"`
}

func (q *Queries) UpsertSPEOLCache(ctx context.Context, arg UpsertSPEOLCacheParams) error {
	_, err := q.db.Exec(ctx, upsertSPEOLCache, arg.Product, arg.Cycle, arg.Payload)
	return err
}

const upsertSPFindingByRawID = `-- name: UpsertSPFindingByRawID :one

INSERT INTO vb_findings
  (org_id, asset_id, cve_id, title, description, severity,
   cvss_score, status, scanner, raw_id, sources, sla_due_at,
   reopen_count, occurrence_count, last_seen_at)
VALUES
  ($1, $2, $3, $4, $5, $6,
   $7, $8, $9, $10, $11, $12,
   0, 1, NOW())
ON CONFLICT (org_id, raw_id, scanner) DO UPDATE
  SET title            = EXCLUDED.title,
      description      = EXCLUDED.description,
      severity         = EXCLUDED.severity,
      cvss_score       = EXCLUDED.cvss_score,
      sla_due_at       = EXCLUDED.sla_due_at,
      occurrence_count = vb_findings.occurrence_count + 1,
      last_seen_at     = NOW(),
      updated_at       = NOW()
RETURNING id, org_id, asset_id, scan_id, cve_id,
          title, description, severity,
          cvss_score, epss_score, epss_percentile, risk_score,
          status, scanner, raw_id, sources, template_id,
          assigned_to, justification,
          reopen_count, occurrence_count,
          last_seen_at, sla_due_at, created_at, updated_at
`

type UpsertSPFindingByRawIDParams struct {
	OrgID       string             `json:"org_id"`
	AssetID     string             `json:"asset_id"`
	CveID       pgtype.Text        `json:"cve_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Severity    string             `json:"severity"`
	CvssScore   pgtype.Numeric     `json:"cvss_score"`
	Status      string             `json:"status"`
	Scanner     string             `json:"scanner"`
	RawID       pgtype.Text        `json:"raw_id"`
	Sources     []string           `json:"sources"`
	SlaDueAt    pgtype.Timestamptz `json:"sla_due_at"`
}

// ── Findings Upsert (single, by raw_id) ─────────────────────────────────────
// Single-shot INSERT...ON CONFLICT for importer flows (SARIF/CycloneDX/CSV).
// Conflict key: (org_id, raw_id, scanner). Multi-row Upserts with conditional
// dedup keys (cve_id vs template_id) remain procedural in the repo because
// the conditional INSERT-vs-UPDATE branch isn't expressible in a single sqlc query.
func (q *Queries) UpsertSPFindingByRawID(ctx context.Context, arg UpsertSPFindingByRawIDParams) (VbFindings, error) {
	row := q.db.QueryRow(ctx, upsertSPFindingByRawID,
		arg.OrgID,
		arg.AssetID,
		arg.CveID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.CvssScore,
		arg.Status,
		arg.Scanner,
		arg.RawID,
		arg.Sources,
		arg.SlaDueAt,
	)
	var i VbFindings
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssetID,
		&i.ScanID,
		&i.CveID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.CvssScore,
		&i.EpssScore,
		&i.EpssPercentile,
		&i.RiskScore,
		&i.Status,
		&i.Scanner,
		&i.RawID,
		&i.Sources,
		&i.TemplateID,
		&i.AssignedTo,
		&i.Justification,
		&i.ReopenCount,
		&i.OccurrenceCount,
		&i.LastSeenAt,
		&i.SlaDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSPSLAConfig = `-- name: UpsertSPSLAConfig :exec
INSERT INTO vb_sla_config (org_id, critical_days, high_days, medium_days, low_days, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (org_id) DO UPDATE
  SET critical_days = EXCLUDED.critical_days,
      high_days     = EXCLUDED.high_days,
      medium_days   = EXCLUDED.medium_days,
      low_days      = EXCLUDED.low_days,
      updated_at    = NOW()
`

type UpsertSPSLAConfigParams struct {
	OrgID        string `json:"org_id"`
	CriticalDays int32  `json:"critical_days"`
	HighDays     int32  `json:"high_days"`
	MediumDays   int32  `json:"medium_days"`
	LowDays      int32  `json:"low_days"`
}

func (q *Queries) UpsertSPSLAConfig(ctx context.Context, arg UpsertSPSLAConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSPSLAConfig,
		arg.OrgID,
		arg.CriticalDays,
		arg.HighDays,
		arg.MediumDays,
		arg.LowDays,
	)
	return err
}

const listSPComponentsBySBOMFull = `-- name: ListSPComponentsBySBOMFull :many
SELECT c.id::text, c.name, c.version, COALESCE(c.purl, '') AS purl,
       c.eol_status,
       CASE WHEN c.eol_date IS NOT NULL THEN c.eol_date::text ELSE NULL END AS eol_date,
       s.asset_id::text AS asset_id
FROM vb_components c
JOIN vb_sboms s ON s.id = c.sbom_id
WHERE c.sbom_id = $1::uuid
ORDER BY c.name, c.version
`

type ListSPComponentsBySBOMFullRow struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Version   string  `json:"version"`
	PURL      string  `json:"purl"`
	EOLStatus string  `json:"eol_status"`
	EOLDate   *string `json:"eol_date"`
	AssetID   string  `json:"asset_id"`
}

func (q *Queries) ListSPComponentsBySBOMFull(ctx context.Context, sbomID string) ([]ListSPComponentsBySBOMFullRow, error) {
	rows, err := q.db.Query(ctx, listSPComponentsBySBOMFull, sbomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSPComponentsBySBOMFullRow{}
	for rows.Next() {
		var i ListSPComponentsBySBOMFullRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Version, &i.PURL, &i.EOLStatus, &i.EOLDate, &i.AssetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSPScanOrgID = `-- name: GetSPScanOrgID :one
SELECT org_id::text FROM vb_scans WHERE id = $1::uuid
`

func (q *Queries) GetSPScanOrgID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSPScanOrgID, id)
	var orgID string
	err := row.Scan(&orgID)
	return orgID, err
}

const batchUpdateSPComponentEOL = `-- name: BatchUpdateSPComponentEOL :exec
UPDATE vb_components AS c
SET eol_status     = v.status,
    eol_date       = v.eol_date::date,
    eol_checked_at = NOW()
FROM (
    SELECT
        UNNEST($1::uuid[])  AS id,
        UNNEST($2::text[])  AS status,
        UNNEST($3::text[])  AS eol_date
) AS v
WHERE c.id = v.id
`

type BatchUpdateSPComponentEOLParams struct {
	Ids      []string  `json:"ids"`
	Statuses []string  `json:"statuses"`
	Dates    []*string `json:"dates"`
}

func (q *Queries) BatchUpdateSPComponentEOL(ctx context.Context, arg BatchUpdateSPComponentEOLParams) error {
	_, err := q.db.Exec(ctx, batchUpdateSPComponentEOL, arg.Ids, arg.Statuses, arg.Dates)
	return err
}
