// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secvault.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSVEnvironment = `-- name: CreateSVEnvironment :one

INSERT INTO so_environments (project_id, org_id, name)
VALUES ($1, $2, $3)
RETURNING id, project_id, org_id, name, created_at
`

type CreateSVEnvironmentParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
	Name      string `json:"name"`
}

// ── Environments ────────────────────────────────────────────────────────────
func (q *Queries) CreateSVEnvironment(ctx context.Context, arg CreateSVEnvironmentParams) (SoEnvironments, error) {
	row := q.db.QueryRow(ctx, createSVEnvironment, arg.ProjectID, arg.OrgID, arg.Name)
	var i SoEnvironments
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createSVProject = `-- name: CreateSVProject :one


INSERT INTO so_projects (org_id, name, slug, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, slug, description, created_by, created_at
`

type CreateSVProjectParams struct {
	OrgID       string      `json:"org_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	CreatedBy   string      `json:"created_by"`
}

type CreateSVProjectRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// SecVault queries — migrated to sqlc in Sprint 11+ (ADR-0005, inkrementell).
//
// Migrationspfad:
//
//	✅ Projects, Environments, AccessLog, RotationPolicies — sqlc (this file)
//	⏳ Secrets — bleibt embedded SQL in repository.go (Crypto-Felder + dynamische
//	   Spalten-Auswahl je nach decrypt-Strategie machen sqlc-Generierung holprig).
//	   Migration on-demand bei nächstem Secrets-Refactor.
//
// ── Projects ────────────────────────────────────────────────────────────────
func (q *Queries) CreateSVProject(ctx context.Context, arg CreateSVProjectParams) (CreateSVProjectRow, error) {
	row := q.db.QueryRow(ctx, createSVProject,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CreatedBy,
	)
	var i CreateSVProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSVEnvironment = `-- name: DeleteSVEnvironment :execrows
DELETE FROM so_environments WHERE id = $1 AND org_id = $2
`

type DeleteSVEnvironmentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteSVEnvironment(ctx context.Context, arg DeleteSVEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSVEnvironment, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSVProject = `-- name: DeleteSVProject :execrows
DELETE FROM so_projects WHERE id = $1 AND org_id = $2
`

type DeleteSVProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteSVProject(ctx context.Context, arg DeleteSVProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSVProject, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSVEnvironment = `-- name: GetSVEnvironment :one
SELECT id, project_id, org_id, name, created_at
FROM so_environments
WHERE id = $1 AND org_id = $2
`

type GetSVEnvironmentParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSVEnvironment(ctx context.Context, arg GetSVEnvironmentParams) (SoEnvironments, error) {
	row := q.db.QueryRow(ctx, getSVEnvironment, arg.ID, arg.OrgID)
	var i SoEnvironments
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSVProject = `-- name: GetSVProject :one
SELECT id, org_id, name, slug, description, created_by, created_at
FROM so_projects
WHERE id = $1 AND org_id = $2
`

type GetSVProjectParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

type GetSVProjectRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSVProject(ctx context.Context, arg GetSVProjectParams) (GetSVProjectRow, error) {
	row := q.db.QueryRow(ctx, getSVProject, arg.ID, arg.OrgID)
	var i GetSVProjectRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertSVAccessLog = `-- name: InsertSVAccessLog :exec

INSERT INTO so_access_log
  (secret_id, org_id, accessed_by, access_via, ip_address, user_agent)
VALUES
  ($1, $2, $3, $4, $5, $6)
`

type InsertSVAccessLogParams struct {
	SecretID   string      `json:"secret_id"`
	OrgID      string      `json:"org_id"`
	AccessedBy pgtype.UUID `json:"accessed_by"`
	AccessVia  string      `json:"access_via"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

// ── Access Log ──────────────────────────────────────────────────────────────
func (q *Queries) InsertSVAccessLog(ctx context.Context, arg InsertSVAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertSVAccessLog,
		arg.SecretID,
		arg.OrgID,
		arg.AccessedBy,
		arg.AccessVia,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const listSVAccessLog = `-- name: ListSVAccessLog :many
SELECT id, secret_id, org_id, accessed_by, access_via,
       ip_address, user_agent, accessed_at
FROM so_access_log
WHERE org_id = $1
ORDER BY accessed_at DESC
LIMIT 500
`

func (q *Queries) ListSVAccessLog(ctx context.Context, orgID string) ([]SoAccessLog, error) {
	rows, err := q.db.Query(ctx, listSVAccessLog, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoAccessLog{}
	for rows.Next() {
		var i SoAccessLog
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.OrgID,
			&i.AccessedBy,
			&i.AccessVia,
			&i.IpAddress,
			&i.UserAgent,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSVEnvironments = `-- name: ListSVEnvironments :many
SELECT id, project_id, org_id, name, created_at
FROM so_environments
WHERE project_id = $1 AND org_id = $2
ORDER BY name
`

type ListSVEnvironmentsParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) ListSVEnvironments(ctx context.Context, arg ListSVEnvironmentsParams) ([]SoEnvironments, error) {
	rows, err := q.db.Query(ctx, listSVEnvironments, arg.ProjectID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoEnvironments{}
	for rows.Next() {
		var i SoEnvironments
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSVProjects = `-- name: ListSVProjects :many
SELECT id, org_id, name, slug, description, created_by, created_at
FROM so_projects
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListSVProjectsRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedBy   string             `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSVProjects(ctx context.Context, orgID string) ([]ListSVProjectsRow, error) {
	rows, err := q.db.Query(ctx, listSVProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSVProjectsRow{}
	for rows.Next() {
		var i ListSVProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ── Access Log helpers ───────────────────────────────────────────────────────

const getSVAccessLog = `-- name: GetSVAccessLog :many
SELECT id::text, secret_id::text,
       accessed_by::text, access_via,
       ip_address, user_agent, accessed_at
FROM so_access_log
WHERE secret_id = $1::uuid
  AND org_id = $2::uuid
ORDER BY accessed_at DESC
LIMIT $3 OFFSET $4`

type GetSVAccessLogParams struct {
	SecretID string `json:"secret_id"`
	OrgID    string `json:"org_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type GetSVAccessLogRow struct {
	ID         string             `json:"id"`
	SecretID   string             `json:"secret_id"`
	AccessedBy pgtype.Text        `json:"accessed_by"`
	AccessVia  string             `json:"access_via"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
}

func (q *Queries) GetSVAccessLog(ctx context.Context, arg GetSVAccessLogParams) ([]GetSVAccessLogRow, error) {
	rows, err := q.db.Query(ctx, getSVAccessLog, arg.SecretID, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSVAccessLogRow{}
	for rows.Next() {
		var i GetSVAccessLogRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.AccessedBy,
			&i.AccessVia,
			&i.IpAddress,
			&i.UserAgent,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSVProjectAccessLog = `-- name: CountSVProjectAccessLog :one
SELECT COUNT(*)::int
FROM so_access_log al
JOIN so_secrets s ON s.id = al.secret_id
JOIN so_environments e ON e.id = s.environment_id
WHERE e.project_id = $1::uuid
  AND al.org_id = $2::uuid`

type CountSVProjectAccessLogParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) CountSVProjectAccessLog(ctx context.Context, arg CountSVProjectAccessLogParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSVProjectAccessLog, arg.ProjectID, arg.OrgID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const listSVProjectAccessLog = `-- name: ListSVProjectAccessLog :many
SELECT
    al.id::text,
    s.key AS secret_key,
    al.access_via,
    al.accessed_by::text,
    al.ip_address,
    al.accessed_at
FROM so_access_log al
JOIN so_secrets s ON s.id = al.secret_id
JOIN so_environments e ON e.id = s.environment_id
WHERE e.project_id = $1::uuid
  AND al.org_id = $2::uuid
ORDER BY al.accessed_at DESC
LIMIT $3 OFFSET $4`

type ListSVProjectAccessLogParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListSVProjectAccessLogRow struct {
	ID         string             `json:"id"`
	SecretKey  string             `json:"secret_key"`
	AccessVia  string             `json:"access_via"`
	AccessedBy pgtype.Text        `json:"accessed_by"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	AccessedAt pgtype.Timestamptz `json:"accessed_at"`
}

func (q *Queries) ListSVProjectAccessLog(ctx context.Context, arg ListSVProjectAccessLogParams) ([]ListSVProjectAccessLogRow, error) {
	rows, err := q.db.Query(ctx, listSVProjectAccessLog, arg.ProjectID, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSVProjectAccessLogRow{}
	for rows.Next() {
		var i ListSVProjectAccessLogRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretKey,
			&i.AccessVia,
			&i.AccessedBy,
			&i.IpAddress,
			&i.AccessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ── Secrets (metadata only) ──────────────────────────────────────────────────

const updateSVSecretAccess = `-- name: UpdateSVSecretAccess :exec
UPDATE so_secrets
SET access_count     = access_count + 1,
    last_accessed_at = NOW()
WHERE id = $1::uuid`

func (q *Queries) UpdateSVSecretAccess(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateSVSecretAccess, id)
	return err
}

const listSVSecretKeys = `-- name: ListSVSecretKeys :many
SELECT id::text, key, version, rotation_due_at, last_rotated_at, last_accessed_at,
       access_count, created_at, updated_at
FROM so_secrets
WHERE environment_id = $1::uuid AND org_id = $2::uuid
ORDER BY key ASC`

type ListSVSecretKeysParams struct {
	EnvironmentID string `json:"environment_id"`
	OrgID         string `json:"org_id"`
}

type ListSVSecretKeysRow struct {
	ID             string             `json:"id"`
	Key            string             `json:"key"`
	Version        int32              `json:"version"`
	RotationDueAt  pgtype.Timestamptz `json:"rotation_due_at"`
	LastRotatedAt  pgtype.Timestamptz `json:"last_rotated_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	AccessCount    int64              `json:"access_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSVSecretKeys(ctx context.Context, arg ListSVSecretKeysParams) ([]ListSVSecretKeysRow, error) {
	rows, err := q.db.Query(ctx, listSVSecretKeys, arg.EnvironmentID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSVSecretKeysRow{}
	for rows.Next() {
		var i ListSVSecretKeysRow
		if err := rows.Scan(
			&i.ID, &i.Key, &i.Version,
			&i.RotationDueAt, &i.LastRotatedAt, &i.LastAccessedAt,
			&i.AccessCount, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSVSecret = `-- name: DeleteSVSecret :execrows
DELETE FROM so_secrets
WHERE environment_id = $1::uuid AND org_id = $2::uuid AND key = $3`

type DeleteSVSecretParams struct {
	EnvironmentID string `json:"environment_id"`
	OrgID         string `json:"org_id"`
	Key           string `json:"key"`
}

func (q *Queries) DeleteSVSecret(ctx context.Context, arg DeleteSVSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSVSecret, arg.EnvironmentID, arg.OrgID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSVSecretIDByKey = `-- name: GetSVSecretIDByKey :one
SELECT id::text FROM so_secrets
WHERE environment_id = $1::uuid AND org_id = $2::uuid AND key = $3`

type GetSVSecretIDByKeyParams struct {
	EnvironmentID string `json:"environment_id"`
	OrgID         string `json:"org_id"`
	Key           string `json:"key"`
}

func (q *Queries) GetSVSecretIDByKey(ctx context.Context, arg GetSVSecretIDByKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, getSVSecretIDByKey, arg.EnvironmentID, arg.OrgID, arg.Key)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSVSecretByKey = `-- name: GetSVSecretByKey :one
SELECT id::text, key, version,
       rotation_due_at, last_rotated_at, last_accessed_at,
       access_count, created_at, updated_at
FROM so_secrets
WHERE environment_id = $1::uuid AND key = $2 AND org_id = $3::uuid`

type GetSVSecretByKeyParams struct {
	EnvironmentID string `json:"environment_id"`
	Key           string `json:"key"`
	OrgID         string `json:"org_id"`
}

type GetSVSecretByKeyRow struct {
	ID             string             `json:"id"`
	Key            string             `json:"key"`
	Version        int32              `json:"version"`
	RotationDueAt  pgtype.Timestamptz `json:"rotation_due_at"`
	LastRotatedAt  pgtype.Timestamptz `json:"last_rotated_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
	AccessCount    int64              `json:"access_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSVSecretByKey(ctx context.Context, arg GetSVSecretByKeyParams) (GetSVSecretByKeyRow, error) {
	row := q.db.QueryRow(ctx, getSVSecretByKey, arg.EnvironmentID, arg.Key, arg.OrgID)
	var i GetSVSecretByKeyRow
	err := row.Scan(
		&i.ID, &i.Key, &i.Version,
		&i.RotationDueAt, &i.LastRotatedAt, &i.LastAccessedAt,
		&i.AccessCount, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listSVProjectSecrets = `-- name: ListSVProjectSecrets :many
SELECT s.id::text, s.key, s.version,
       s.rotation_due_at, s.last_rotated_at, s.last_accessed_at,
       s.access_count, s.created_at, s.updated_at
FROM so_secrets s
JOIN so_environments e ON e.id = s.environment_id
WHERE e.project_id = $1::uuid AND s.org_id = $2::uuid
ORDER BY s.key ASC`

type ListSVProjectSecretsParams struct {
	ProjectID string `json:"project_id"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) ListSVProjectSecrets(ctx context.Context, arg ListSVProjectSecretsParams) ([]ListSVSecretKeysRow, error) {
	rows, err := q.db.Query(ctx, listSVProjectSecrets, arg.ProjectID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSVSecretKeysRow{}
	for rows.Next() {
		var i ListSVSecretKeysRow
		if err := rows.Scan(
			&i.ID, &i.Key, &i.Version,
			&i.RotationDueAt, &i.LastRotatedAt, &i.LastAccessedAt,
			&i.AccessCount, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ── Share links ──────────────────────────────────────────────────────────────

const createSVShareLink = `-- name: CreateSVShareLink :one
INSERT INTO so_share_links (secret_id, org_id, token_hash, expires_at, created_by)
VALUES ($1::uuid, $2::uuid, $3, $4, $5::uuid)
RETURNING id::text, secret_id::text, expires_at, created_at`

type CreateSVShareLinkParams struct {
	SecretID  string    `json:"secret_id"`
	OrgID     string    `json:"org_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedBy string    `json:"created_by"`
}

type CreateSVShareLinkRow struct {
	ID        string             `json:"id"`
	SecretID  string             `json:"secret_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSVShareLink(ctx context.Context, arg CreateSVShareLinkParams) (CreateSVShareLinkRow, error) {
	row := q.db.QueryRow(ctx, createSVShareLink,
		arg.SecretID, arg.OrgID, arg.TokenHash, arg.ExpiresAt, arg.CreatedBy)
	var i CreateSVShareLinkRow
	err := row.Scan(&i.ID, &i.SecretID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const getSVShareLink = `-- name: GetSVShareLink :one
SELECT id::text, secret_id::text, expires_at, used_at, created_at
FROM so_share_links
WHERE token_hash = $1`

type GetSVShareLinkRow struct {
	ID        string             `json:"id"`
	SecretID  string             `json:"secret_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSVShareLink(ctx context.Context, tokenHash string) (GetSVShareLinkRow, error) {
	row := q.db.QueryRow(ctx, getSVShareLink, tokenHash)
	var i GetSVShareLinkRow
	err := row.Scan(&i.ID, &i.SecretID, &i.ExpiresAt, &i.UsedAt, &i.CreatedAt)
	return i, err
}

const getSVShareLinkOrgID = `-- name: GetSVShareLinkOrgID :one
SELECT org_id::text FROM so_share_links WHERE id = $1::uuid`

func (q *Queries) GetSVShareLinkOrgID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSVShareLinkOrgID, id)
	var orgID string
	err := row.Scan(&orgID)
	return orgID, err
}

const markSVShareLinkUsed = `-- name: MarkSVShareLinkUsed :exec
UPDATE so_share_links SET used_at = NOW()
WHERE id = $1::uuid AND org_id = $2::uuid`

type MarkSVShareLinkUsedParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) MarkSVShareLinkUsed(ctx context.Context, arg MarkSVShareLinkUsedParams) error {
	_, err := q.db.Exec(ctx, markSVShareLinkUsed, arg.ID, arg.OrgID)
	return err
}

// ── API tokens ───────────────────────────────────────────────────────────────

const createSVAPIToken = `-- name: CreateSVAPIToken :one
INSERT INTO api_keys (org_id, created_by, name, key_hash, key_prefix, scopes, expires_at)
VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6, $7)
RETURNING id::text, name, key_prefix, scopes, expires_at, last_used_at, revoked_at, created_at`

type CreateSVAPITokenParams struct {
	OrgID     string             `json:"org_id"`
	CreatedBy string             `json:"created_by"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateSVAPITokenRow struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSVAPIToken(ctx context.Context, arg CreateSVAPITokenParams) (CreateSVAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createSVAPIToken,
		arg.OrgID, arg.CreatedBy, arg.Name, arg.KeyHash, arg.KeyPrefix, arg.Scopes, arg.ExpiresAt)
	var i CreateSVAPITokenRow
	err := row.Scan(
		&i.ID, &i.Name, &i.KeyPrefix, &i.Scopes,
		&i.ExpiresAt, &i.LastUsedAt, &i.RevokedAt, &i.CreatedAt,
	)
	return i, err
}

const listSVAPITokens = `-- name: ListSVAPITokens :many
SELECT id::text, name, key_prefix, scopes, expires_at, last_used_at, revoked_at, created_at
FROM api_keys
WHERE org_id = $1::uuid AND created_by = $2::uuid
  AND $3 = ANY(scopes)
ORDER BY created_at DESC`

type ListSVAPITokensParams struct {
	OrgID     string `json:"org_id"`
	CreatedBy string `json:"created_by"`
	Scope     string `json:"scope"`
}

func (q *Queries) ListSVAPITokens(ctx context.Context, arg ListSVAPITokensParams) ([]CreateSVAPITokenRow, error) {
	rows, err := q.db.Query(ctx, listSVAPITokens, arg.OrgID, arg.CreatedBy, arg.Scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreateSVAPITokenRow{}
	for rows.Next() {
		var i CreateSVAPITokenRow
		if err := rows.Scan(
			&i.ID, &i.Name, &i.KeyPrefix, &i.Scopes,
			&i.ExpiresAt, &i.LastUsedAt, &i.RevokedAt, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSVAPIToken = `-- name: RevokeSVAPIToken :execrows
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1::uuid AND org_id = $2::uuid AND created_by = $3::uuid
  AND $4 = ANY(scopes)
  AND revoked_at IS NULL`

type RevokeSVAPITokenParams struct {
	ID        string `json:"id"`
	OrgID     string `json:"org_id"`
	CreatedBy string `json:"created_by"`
	Scope     string `json:"scope"`
}

func (q *Queries) RevokeSVAPIToken(ctx context.Context, arg RevokeSVAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSVAPIToken, arg.ID, arg.OrgID, arg.CreatedBy, arg.Scope)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// ── Environment helpers ──────────────────────────────────────────────────────

const getSVEnvProjectID = `-- name: GetSVEnvProjectID :one
SELECT project_id::text FROM so_environments WHERE id = $1::uuid AND org_id = $2::uuid`

type GetSVEnvProjectIDParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSVEnvProjectID(ctx context.Context, arg GetSVEnvProjectIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getSVEnvProjectID, arg.ID, arg.OrgID)
	var projectID string
	err := row.Scan(&projectID)
	return projectID, err
}

const getSVSecretProjectID = `-- name: GetSVSecretProjectID :one
SELECT e.project_id::text
FROM so_secrets s
JOIN so_environments e ON e.id = s.environment_id
WHERE s.id = $1::uuid`

func (q *Queries) GetSVSecretProjectID(ctx context.Context, secretID string) (string, error) {
	row := q.db.QueryRow(ctx, getSVSecretProjectID, secretID)
	var projectID string
	err := row.Scan(&projectID)
	return projectID, err
}

// ── Git scans ────────────────────────────────────────────────────────────────

const createSVGitScan = `-- name: CreateSVGitScan :one
INSERT INTO so_git_scans (org_id, repo_url, branch)
VALUES ($1::uuid, $2, $3)
RETURNING id::text, org_id::text, repo_url, branch, status,
          finding_count, open_count, dismissed_count,
          COALESCE(error_message,'') AS error_message, scanned_at, created_at`

type CreateSVGitScanParams struct {
	OrgID   string `json:"org_id"`
	RepoURL string `json:"repo_url"`
	Branch  string `json:"branch"`
}

type SVGitScanRow struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	RepoURL        string             `json:"repo_url"`
	Branch         string             `json:"branch"`
	Status         string             `json:"status"`
	FindingCount   int32              `json:"finding_count"`
	OpenCount      int32              `json:"open_count"`
	DismissedCount int32              `json:"dismissed_count"`
	ErrorMessage   string             `json:"error_message"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSVGitScan(ctx context.Context, arg CreateSVGitScanParams) (SVGitScanRow, error) {
	row := q.db.QueryRow(ctx, createSVGitScan, arg.OrgID, arg.RepoURL, arg.Branch)
	var i SVGitScanRow
	err := row.Scan(
		&i.ID, &i.OrgID, &i.RepoURL, &i.Branch, &i.Status,
		&i.FindingCount, &i.OpenCount, &i.DismissedCount,
		&i.ErrorMessage, &i.ScannedAt, &i.CreatedAt,
	)
	return i, err
}

const getSVGitScan = `-- name: GetSVGitScan :one
SELECT id::text, org_id::text, repo_url, branch, status,
       finding_count, open_count, dismissed_count,
       COALESCE(error_message,'') AS error_message, scanned_at, created_at
FROM so_git_scans WHERE id=$1::uuid AND org_id=$2::uuid`

type GetSVGitScanParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetSVGitScan(ctx context.Context, arg GetSVGitScanParams) (SVGitScanRow, error) {
	row := q.db.QueryRow(ctx, getSVGitScan, arg.ID, arg.OrgID)
	var i SVGitScanRow
	err := row.Scan(
		&i.ID, &i.OrgID, &i.RepoURL, &i.Branch, &i.Status,
		&i.FindingCount, &i.OpenCount, &i.DismissedCount,
		&i.ErrorMessage, &i.ScannedAt, &i.CreatedAt,
	)
	return i, err
}

const listSVGitScans = `-- name: ListSVGitScans :many
SELECT id::text, org_id::text, repo_url, branch, status,
       finding_count, open_count, dismissed_count,
       COALESCE(error_message,'') AS error_message, scanned_at, created_at
FROM so_git_scans WHERE org_id=$1::uuid ORDER BY created_at DESC`

func (q *Queries) ListSVGitScans(ctx context.Context, orgID string) ([]SVGitScanRow, error) {
	rows, err := q.db.Query(ctx, listSVGitScans, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SVGitScanRow{}
	for rows.Next() {
		var i SVGitScanRow
		if err := rows.Scan(
			&i.ID, &i.OrgID, &i.RepoURL, &i.Branch, &i.Status,
			&i.FindingCount, &i.OpenCount, &i.DismissedCount,
			&i.ErrorMessage, &i.ScannedAt, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSVGitScanStatus = `-- name: UpdateSVGitScanStatus :exec
UPDATE so_git_scans
SET status=$1, finding_count=$2, open_count=$3, dismissed_count=$4,
    error_message=$5, scanned_at=$6
WHERE id=$7::uuid AND org_id=$8::uuid`

type UpdateSVGitScanStatusParams struct {
	Status         string             `json:"status"`
	FindingCount   int32              `json:"finding_count"`
	OpenCount      int32              `json:"open_count"`
	DismissedCount int32              `json:"dismissed_count"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	ScannedAt      pgtype.Timestamptz `json:"scanned_at"`
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
}

func (q *Queries) UpdateSVGitScanStatus(ctx context.Context, arg UpdateSVGitScanStatusParams) error {
	_, err := q.db.Exec(ctx, updateSVGitScanStatus,
		arg.Status, arg.FindingCount, arg.OpenCount, arg.DismissedCount,
		arg.ErrorMessage, arg.ScannedAt, arg.ID, arg.OrgID,
	)
	return err
}

// ── Git scan results ─────────────────────────────────────────────────────────

const getSVScanResults = `-- name: GetSVScanResults :many
SELECT id::text, org_id::text, scan_id::text, repo_url,
       COALESCE(commit_hash,'') AS commit_hash,
       file_path, COALESCE(line_number,0) AS line_number,
       pattern_name, match_preview, severity, status,
       COALESCE(dismiss_reason,'') AS dismiss_reason,
       dismiss_count, created_at
FROM so_scan_results
WHERE scan_id=$1::uuid AND org_id=$2::uuid
ORDER BY severity, file_path`

type GetSVScanResultsParams struct {
	ScanID string `json:"scan_id"`
	OrgID  string `json:"org_id"`
}

type SVScanResultRow struct {
	ID            string             `json:"id"`
	OrgID         string             `json:"org_id"`
	ScanID        string             `json:"scan_id"`
	RepoURL       string             `json:"repo_url"`
	CommitHash    string             `json:"commit_hash"`
	FilePath      string             `json:"file_path"`
	LineNumber    int32              `json:"line_number"`
	PatternName   string             `json:"pattern_name"`
	MatchPreview  string             `json:"match_preview"`
	Severity      string             `json:"severity"`
	Status        string             `json:"status"`
	DismissReason string             `json:"dismiss_reason"`
	DismissCount  int32              `json:"dismiss_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSVScanResults(ctx context.Context, arg GetSVScanResultsParams) ([]SVScanResultRow, error) {
	rows, err := q.db.Query(ctx, getSVScanResults, arg.ScanID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SVScanResultRow{}
	for rows.Next() {
		var i SVScanResultRow
		if err := rows.Scan(
			&i.ID, &i.OrgID, &i.ScanID, &i.RepoURL, &i.CommitHash,
			&i.FilePath, &i.LineNumber, &i.PatternName, &i.MatchPreview,
			&i.Severity, &i.Status, &i.DismissReason, &i.DismissCount, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dismissSVScanResult = `-- name: DismissSVScanResult :execrows
UPDATE so_scan_results
SET status='dismissed', dismiss_reason=$1, dismiss_count=dismiss_count+1
WHERE id=$2::uuid AND org_id=$3::uuid`

type DismissSVScanResultParams struct {
	Reason string `json:"reason"`
	ID     string `json:"id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) DismissSVScanResult(ctx context.Context, arg DismissSVScanResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissSVScanResult, arg.Reason, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSVDismissals = `-- name: CountSVDismissals :one
SELECT COALESCE(SUM(dismiss_count), 0)::int
FROM so_scan_results
WHERE org_id=$1::uuid AND pattern_name=$2 AND file_path=$3 AND status='dismissed'`

type CountSVDismissalsParams struct {
	OrgID       string `json:"org_id"`
	PatternName string `json:"pattern_name"`
	FilePath    string `json:"file_path"`
}

func (q *Queries) CountSVDismissals(ctx context.Context, arg CountSVDismissalsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSVDismissals, arg.OrgID, arg.PatternName, arg.FilePath)
	var count int32
	err := row.Scan(&count)
	return count, err
}

// ── Rotation policies ────────────────────────────────────────────────────────

const upsertSVRotationPolicy = `-- name: UpsertSVRotationPolicy :one
INSERT INTO so_rotation_policies (org_id, secret_id, interval_days, next_rotation_at)
VALUES ($1::uuid, $2::uuid, $3, $4)
ON CONFLICT (secret_id) DO UPDATE
  SET interval_days=EXCLUDED.interval_days,
      next_rotation_at=EXCLUDED.next_rotation_at
RETURNING id::text, org_id::text, secret_id::text, interval_days,
          last_rotated_at, next_rotation_at, is_active, created_at`

type UpsertSVRotationPolicyParams struct {
	OrgID          string    `json:"org_id"`
	SecretID       string    `json:"secret_id"`
	IntervalDays   int32     `json:"interval_days"`
	NextRotationAt time.Time `json:"next_rotation_at"`
}

type SVRotationPolicyRow struct {
	ID             string             `json:"id"`
	OrgID          string             `json:"org_id"`
	SecretID       string             `json:"secret_id"`
	IntervalDays   int32              `json:"interval_days"`
	LastRotatedAt  pgtype.Timestamptz `json:"last_rotated_at"`
	NextRotationAt pgtype.Timestamptz `json:"next_rotation_at"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertSVRotationPolicy(ctx context.Context, arg UpsertSVRotationPolicyParams) (SVRotationPolicyRow, error) {
	row := q.db.QueryRow(ctx, upsertSVRotationPolicy,
		arg.OrgID, arg.SecretID, arg.IntervalDays, arg.NextRotationAt)
	var i SVRotationPolicyRow
	err := row.Scan(
		&i.ID, &i.OrgID, &i.SecretID, &i.IntervalDays,
		&i.LastRotatedAt, &i.NextRotationAt, &i.IsActive, &i.CreatedAt,
	)
	return i, err
}

const getSVRotationPolicy = `-- name: GetSVRotationPolicy :one
SELECT id::text, org_id::text, secret_id::text, interval_days,
       last_rotated_at, next_rotation_at, is_active, created_at
FROM so_rotation_policies WHERE secret_id=$1::uuid AND org_id=$2::uuid`

type GetSVRotationPolicyParams struct {
	SecretID string `json:"secret_id"`
	OrgID    string `json:"org_id"`
}

func (q *Queries) GetSVRotationPolicy(ctx context.Context, arg GetSVRotationPolicyParams) (SVRotationPolicyRow, error) {
	row := q.db.QueryRow(ctx, getSVRotationPolicy, arg.SecretID, arg.OrgID)
	var i SVRotationPolicyRow
	err := row.Scan(
		&i.ID, &i.OrgID, &i.SecretID, &i.IntervalDays,
		&i.LastRotatedAt, &i.NextRotationAt, &i.IsActive, &i.CreatedAt,
	)
	return i, err
}

const updateSVRotationAfterRotate = `-- name: UpdateSVRotationAfterRotate :exec
UPDATE so_rotation_policies
SET last_rotated_at=NOW(), next_rotation_at=$1
WHERE secret_id=$2::uuid AND org_id=$3::uuid`

type UpdateSVRotationAfterRotateParams struct {
	NextRotationAt time.Time `json:"next_rotation_at"`
	SecretID       string    `json:"secret_id"`
	OrgID          string    `json:"org_id"`
}

func (q *Queries) UpdateSVRotationAfterRotate(ctx context.Context, arg UpdateSVRotationAfterRotateParams) error {
	_, err := q.db.Exec(ctx, updateSVRotationAfterRotate, arg.NextRotationAt, arg.SecretID, arg.OrgID)
	return err
}
